// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

// Locale tags are the file names, upper-cased, so a reader can find the
// source of any table in one step. Kotlin wants camelCase functions and a
// locale is not a word; renaming them would break that correspondence for
// a convention no human reads here. Lines are long because a translated
// string is as long as it is.
// Repeated literals are the point: many languages share a word, and a
// table that extracted them into constants would stop being readable as
// the source files it mirrors.
@file:Suppress("FunctionNaming", "MaxLineLength", "LargeClass", "StringLiteralDuplication", "LongMethod", "TooManyFunctions")

package tv.nomercy.player.video.session

// The lock screen's season label, in every language it ships.
//
// Generated by scripts/generate-player-translations.py from the same
// media-session/i18n/*.ts files the browser loads, so a native
// viewer reads the string a web viewer reads rather than a rewording of it.
//
// 79 locales, 1 keys. Generated because hand-maintaining that is how one
// locale silently keeps a string the web changed two releases ago.
//
// Do not edit — regenerate.
public object MediaSessionTranslations {

    // English is the canonical schema on the web: every other file is typed
    // against it, so a key missing anywhere is a compile error there. Here it
    // is the fallback, which is the same guarantee said differently — a
    // locale missing a key reads English rather than reading a key.
    public const val FALLBACK: String = "en"

    // A function per locale, and a map of references rather than of maps.
    //
    // Built the obvious way — one object holding eighty map literals — a
    // table this wide lands in a single static initializer and the JVM
    // refuses the class outright: 'Method too large: <clinit>', because
    // nine thousand entries is past the 64K bytecode limit for one method.
    // The generator emits this shape for every table it writes rather than
    // only the wide ones, so a table that grows does not one day need a
    // different shape than the one its readers were written against.
    //
    // Split like this each locale is its own small method, and the
    // initializer holds eighty references. It also means a player that only
    // ever renders one language only ever builds one map.
    public fun of(locale: String): Map<String, String> =
        (LOCALES[locale] ?: LOCALES[locale.substringBefore('-')] ?: LOCALES.getValue(FALLBACK))()

    // A key with no value in this locale falls back to English rather than
    // rendering the key itself, which is what a viewer sees as
    // 'plugin.media-session.season' in the middle of their player.
    public fun get(locale: String, key: String): String =
        of(locale)[key] ?: LOCALES.getValue(FALLBACK)()[key] ?: key

    public val available: Set<String> get() = LOCALES.keys

    private fun AF(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Seisoen {season}",
    )

    private fun AR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "الموسم {season}",
    )

    private fun BG(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Сезон {season}",
    )

    private fun BN(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "সিজন {season}",
    )

    private fun CA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Temporada {season}",
    )

    private fun CS(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezóna {season}",
    )

    private fun CY(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Tymor {season}",
    )

    private fun DA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sæson {season}",
    )

    private fun DE(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Staffel {season}",
    )

    private fun EL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Σεζόν {season}",
    )

    private fun EN(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Season {season}",
    )

    private fun ES(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Temporada {season}",
    )

    private fun ET(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Hooaeg {season}",
    )

    private fun EU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}. denboraldia",
    )

    private fun FA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "فصل {season}",
    )

    private fun FI(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Kausi {season}",
    )

    private fun FR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Saison {season}",
    )

    private fun GA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Séasúr {season}",
    )

    private fun GL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Temporada {season}",
    )

    private fun GU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "સીઝન {season}",
    )

    private fun HE(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "עונה {season}",
    )

    private fun HI(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "सीज़न {season}",
    )

    private fun HR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezona {season}",
    )

    private fun HU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}. évad",
    )

    private fun HY(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Եթերաշրջան {season}",
    )

    private fun ID(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Musim {season}",
    )

    private fun IS(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Þáttaröð {season}",
    )

    private fun IT(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Stagione {season}",
    )

    private fun JA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "シーズン {season}",
    )

    private fun KA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "სეზონი {season}",
    )

    private fun KK(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}-маусым",
    )

    private fun KM(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "រដូវកាល {season}",
    )

    private fun KN(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "ಸೀಸನ್ {season}",
    )

    private fun KO(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "시즌 {season}",
    )

    private fun KU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Demsal {season}",
    )

    private fun KY(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}-сезон",
    )

    private fun LO(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "ພາກ {season}",
    )

    private fun LT(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season} sezonas",
    )

    private fun LV(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}. sezona",
    )

    private fun MK(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Сезона {season}",
    )

    private fun ML(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "സീസൺ {season}",
    )

    private fun MN(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}-р улирал",
    )

    private fun MR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "सीझन {season}",
    )

    private fun MS(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Musim {season}",
    )

    private fun MY(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "ရာသီ {season}",
    )

    private fun NB(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sesong {season}",
    )

    private fun NE(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "सिजन {season}",
    )

    private fun NL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Seizoen {season}",
    )

    private fun NN(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sesong {season}",
    )

    private fun NO(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sesong {season}",
    )

    private fun OC(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sason {season}",
    )

    private fun PA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "ਸੀਜ਼ਨ {season}",
    )

    private fun PL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezon {season}",
    )

    private fun PT(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Temporada {season}",
    )

    private fun PT_BR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Temporada {season}",
    )

    private fun RO(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezonul {season}",
    )

    private fun RU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Сезон {season}",
    )

    private fun SI(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "වාරය {season}",
    )

    private fun SK(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Séria {season}",
    )

    private fun SL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezona {season}",
    )

    private fun SQ(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Sezoni {season}",
    )

    private fun SR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Сезона {season}",
    )

    private fun SV(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Säsong {season}",
    )

    private fun SW(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Msimu {season}",
    )

    private fun TA(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "சீசன் {season}",
    )

    private fun TE(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "సీజన్ {season}",
    )

    private fun TG(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Мавсими {season}",
    )

    private fun TH(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "ซีซัน {season}",
    )

    private fun TL(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Season {season}",
    )

    private fun TR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}. Sezon",
    )

    private fun UK(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Сезон {season}",
    )

    private fun UR(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "سیزن {season}",
    )

    private fun UZ(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "{season}-fasl",
    )

    private fun VI(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Mùa {season}",
    )

    private fun XH(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Isizini {season}",
    )

    private fun YO(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Àkókò {season}",
    )

    private fun ZH(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "第 {season} 季",
    )

    private fun ZH_TW(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "第 {season} 季",
    )

    private fun ZU(): Map<String, String> = mapOf(
        "plugin.media-session.season" to "Isizini {season}",
    )

    private val LOCALES: Map<String, () -> Map<String, String>> = mapOf(
        "af" to ::AF,
        "ar" to ::AR,
        "bg" to ::BG,
        "bn" to ::BN,
        "ca" to ::CA,
        "cs" to ::CS,
        "cy" to ::CY,
        "da" to ::DA,
        "de" to ::DE,
        "el" to ::EL,
        "en" to ::EN,
        "es" to ::ES,
        "et" to ::ET,
        "eu" to ::EU,
        "fa" to ::FA,
        "fi" to ::FI,
        "fr" to ::FR,
        "ga" to ::GA,
        "gl" to ::GL,
        "gu" to ::GU,
        "he" to ::HE,
        "hi" to ::HI,
        "hr" to ::HR,
        "hu" to ::HU,
        "hy" to ::HY,
        "id" to ::ID,
        "is" to ::IS,
        "it" to ::IT,
        "ja" to ::JA,
        "ka" to ::KA,
        "kk" to ::KK,
        "km" to ::KM,
        "kn" to ::KN,
        "ko" to ::KO,
        "ku" to ::KU,
        "ky" to ::KY,
        "lo" to ::LO,
        "lt" to ::LT,
        "lv" to ::LV,
        "mk" to ::MK,
        "ml" to ::ML,
        "mn" to ::MN,
        "mr" to ::MR,
        "ms" to ::MS,
        "my" to ::MY,
        "nb" to ::NB,
        "ne" to ::NE,
        "nl" to ::NL,
        "nn" to ::NN,
        "no" to ::NO,
        "oc" to ::OC,
        "pa" to ::PA,
        "pl" to ::PL,
        "pt" to ::PT,
        "pt-BR" to ::PT_BR,
        "ro" to ::RO,
        "ru" to ::RU,
        "si" to ::SI,
        "sk" to ::SK,
        "sl" to ::SL,
        "sq" to ::SQ,
        "sr" to ::SR,
        "sv" to ::SV,
        "sw" to ::SW,
        "ta" to ::TA,
        "te" to ::TE,
        "tg" to ::TG,
        "th" to ::TH,
        "tl" to ::TL,
        "tr" to ::TR,
        "uk" to ::UK,
        "ur" to ::UR,
        "uz" to ::UZ,
        "vi" to ::VI,
        "xh" to ::XH,
        "yo" to ::YO,
        "zh" to ::ZH,
        "zh-TW" to ::ZH_TW,
        "zu" to ::ZU,
    )
}
