// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

// Locale tags are the file names, upper-cased, so a reader can find the
// source of any table in one step. Kotlin wants camelCase functions and a
// locale is not a word; renaming them would break that correspondence for
// a convention no human reads here. Lines are long because a translated
// string is as long as it is.
// Repeated literals are the point: many languages share a word, and a
// table that extracted them into constants would stop being readable as
// the source files it mirrors.
@file:Suppress("FunctionNaming", "MaxLineLength", "LargeClass", "StringLiteralDuplication", "LongMethod", "TooManyFunctions")

package tv.nomercy.player.video.cast

// The cast plugin's strings, in every language it ships.
//
// Generated by scripts/generate-player-translations.py from the same
// cast-sender/i18n/*.ts files the browser loads, so a native
// viewer reads the string a web viewer reads rather than a rewording of it.
//
// 79 locales, 12 keys. Generated because hand-maintaining that is how one
// locale silently keeps a string the web changed two releases ago.
//
// Do not edit — regenerate.
public object CastTranslations {

    // English is the canonical schema on the web: every other file is typed
    // against it, so a key missing anywhere is a compile error there. Here it
    // is the fallback, which is the same guarantee said differently — a
    // locale missing a key reads English rather than reading a key.
    public const val FALLBACK: String = "en"

    // A function per locale, and a map of references rather than of maps.
    //
    // Built the obvious way — one object holding eighty map literals — a
    // table this wide lands in a single static initializer and the JVM
    // refuses the class outright: 'Method too large: <clinit>', because
    // nine thousand entries is past the 64K bytecode limit for one method.
    // The generator emits this shape for every table it writes rather than
    // only the wide ones, so a table that grows does not one day need a
    // different shape than the one its readers were written against.
    //
    // Split like this each locale is its own small method, and the
    // initializer holds eighty references. It also means a player that only
    // ever renders one language only ever builds one map.
    public fun of(locale: String): Map<String, String> =
        (LOCALES[locale] ?: LOCALES[locale.substringBefore('-')] ?: LOCALES.getValue(FALLBACK))()

    // A key with no value in this locale falls back to English rather than
    // rendering the key itself, which is what a viewer sees as
    // 'plugin.cast-sender.action.connect' in the middle of their player.
    public fun get(locale: String, key: String): String =
        of(locale)[key] ?: LOCALES.getValue(FALLBACK)()[key] ?: key

    public val available: Set<String> get() = LOCALES.keys

    private fun AF(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Stuur is nie op hierdie toestel beskikbaar nie.",
        "plugin.cast-sender.connecting" to "Verbind tans met {device}…",
        "plugin.cast-sender.connected" to "Stuur tans na {device}",
        "plugin.cast-sender.disconnected" to "Verbinding met {device} verbreek",
        "plugin.cast-sender.error.session-failed" to "Kon nie die uitsaai-sessie begin nie.",
        "plugin.cast-sender.error.load-failed" to "Die uitsaaitoestel het die media geweier.",
        "plugin.cast-sender.error.generic" to "\\'n Uitsaaifout het voorgekom.",
        "plugin.cast-sender.action.connect" to "Gooi",
        "plugin.cast-sender.action.disconnect" to "Stop uitsaai",
        "plugin.cast-sender.state.buffering" to "Bufferend",
        "plugin.cast-sender.state.playing" to "Speel op {device}",
        "plugin.cast-sender.state.paused" to "Onderbreek op {device}",
    )

    private fun AR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "البث غير متاح على هذا الجهاز.",
        "plugin.cast-sender.connecting" to "جارٍ الاتصال بـ {device}…",
        "plugin.cast-sender.connected" to "البث إلى {device}",
        "plugin.cast-sender.disconnected" to "تم قطع الاتصال بـ {device}",
        "plugin.cast-sender.error.session-failed" to "تعذّر بدء جلسة الإرسال.",
        "plugin.cast-sender.error.load-failed" to "رفض جهاز الإرسال الوسائط.",
        "plugin.cast-sender.error.generic" to "حدث خطأ في الإرسال.",
        "plugin.cast-sender.action.connect" to "بث",
        "plugin.cast-sender.action.disconnect" to "إيقاف الإرسال",
        "plugin.cast-sender.state.buffering" to "جارٍ التحميل المؤقت",
        "plugin.cast-sender.state.playing" to "قيد التشغيل على {device}",
        "plugin.cast-sender.state.paused" to "متوقف مؤقتًا على {device}",
    )

    private fun BG(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Предаването не е налично на това устройство.",
        "plugin.cast-sender.connecting" to "Свързване с {device}…",
        "plugin.cast-sender.connected" to "Предаване към {device}",
        "plugin.cast-sender.disconnected" to "Връзката с {device} е прекъсната",
        "plugin.cast-sender.error.session-failed" to "Сесията за предаване не можа да започне.",
        "plugin.cast-sender.error.load-failed" to "Устройството за предаване отхвърли мултимедията.",
        "plugin.cast-sender.error.generic" to "Възникна грешка при предаване.",
        "plugin.cast-sender.action.connect" to "Излъчване",
        "plugin.cast-sender.action.disconnect" to "Спиране на предаването",
        "plugin.cast-sender.state.buffering" to "Буфериране",
        "plugin.cast-sender.state.playing" to "Възпроизвежда се на {device}",
        "plugin.cast-sender.state.paused" to "Поставено на пауза на {device}",
    )

    private fun BN(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "এই ডিভাইসে কাস্টিং উপলব্ধ নয়।",
        "plugin.cast-sender.connecting" to "{device}-এ সংযোগ করা হচ্ছে…",
        "plugin.cast-sender.connected" to "{device}-এ কাস্ট করা হচ্ছে",
        "plugin.cast-sender.disconnected" to "{device} থেকে সংযোগ বিচ্ছিন্ন হয়েছে",
        "plugin.cast-sender.error.session-failed" to "কাস্ট সেশন শুরু করা যায়নি।",
        "plugin.cast-sender.error.load-failed" to "কাস্ট ডিভাইসটি মিডিয়া প্রত্যাখ্যান করেছে।",
        "plugin.cast-sender.error.generic" to "একটি কাস্ট ত্রুটি ঘটেছে।",
        "plugin.cast-sender.action.connect" to "কাস্ট",
        "plugin.cast-sender.action.disconnect" to "কাস্ট করা বন্ধ করুন",
        "plugin.cast-sender.state.buffering" to "বাফারিং",
        "plugin.cast-sender.state.playing" to "{device}-এ চলছে",
        "plugin.cast-sender.state.paused" to "{device}-এ বিরতি দেওয়া হয়েছে",
    )

    private fun CA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "L\\'emissió no està disponible en aquest dispositiu.",
        "plugin.cast-sender.connecting" to "S\\'està connectant a {device}…",
        "plugin.cast-sender.connected" to "S\\'està emetent a {device}",
        "plugin.cast-sender.disconnected" to "S\\'ha desconnectat de {device}",
        "plugin.cast-sender.error.session-failed" to "No s\\'ha pogut iniciar la sessió de transmissió.",
        "plugin.cast-sender.error.load-failed" to "El dispositiu de transmissió ha rebutjat el contingut.",
        "plugin.cast-sender.error.generic" to "S\\'ha produït un error de transmissió.",
        "plugin.cast-sender.action.connect" to "Emetre",
        "plugin.cast-sender.action.disconnect" to "Atura la transmissió",
        "plugin.cast-sender.state.buffering" to "Carregant memòria intermèdia",
        "plugin.cast-sender.state.playing" to "S\\'està reproduint a {device}",
        "plugin.cast-sender.state.paused" to "En pausa a {device}",
    )

    private fun CS(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Odesílání není na tomto zařízení k dispozici.",
        "plugin.cast-sender.connecting" to "Připojování k {device}…",
        "plugin.cast-sender.connected" to "Odesílání do {device}",
        "plugin.cast-sender.disconnected" to "Odpojeno od {device}",
        "plugin.cast-sender.error.session-failed" to "Relaci přenosu se nepodařilo spustit.",
        "plugin.cast-sender.error.load-failed" to "Zařízení pro přenos odmítlo médium.",
        "plugin.cast-sender.error.generic" to "Došlo k chybě přenosu.",
        "plugin.cast-sender.action.connect" to "Přenést",
        "plugin.cast-sender.action.disconnect" to "Zastavit přenos",
        "plugin.cast-sender.state.buffering" to "Načítání do vyrovnávací paměti",
        "plugin.cast-sender.state.playing" to "Přehrává se na {device}",
        "plugin.cast-sender.state.paused" to "Pozastaveno na {device}",
    )

    private fun CY(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Nid yw castio ar gael ar y ddyfais hon.",
        "plugin.cast-sender.connecting" to "Yn cysylltu â {device}…",
        "plugin.cast-sender.connected" to "Castio i {device}",
        "plugin.cast-sender.disconnected" to "Datgysylltwyd o {device}",
        "plugin.cast-sender.error.session-failed" to "Methwyd dechrau\\'r sesiwn castio.",
        "plugin.cast-sender.error.load-failed" to "Gwrthododd y ddyfais gastio\\'r cyfrwng.",
        "plugin.cast-sender.error.generic" to "Digwyddodd gwall castio.",
        "plugin.cast-sender.action.connect" to "Bwrw",
        "plugin.cast-sender.action.disconnect" to "Stopio castio",
        "plugin.cast-sender.state.buffering" to "Bwffro",
        "plugin.cast-sender.state.playing" to "Yn chwarae ar {device}",
        "plugin.cast-sender.state.paused" to "Wedi\\'i oedi ar {device}",
    )

    private fun DA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting er ikke tilgængelig på denne enhed.",
        "plugin.cast-sender.connecting" to "Opretter forbindelse til {device}…",
        "plugin.cast-sender.connected" to "Caster til {device}",
        "plugin.cast-sender.disconnected" to "Afbrudt fra {device}",
        "plugin.cast-sender.error.session-failed" to "Cast-sessionen kunne ikke startes.",
        "plugin.cast-sender.error.load-failed" to "Cast-enheden afviste mediet.",
        "plugin.cast-sender.error.generic" to "Der opstod en cast-fejl.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Stop cast",
        "plugin.cast-sender.state.buffering" to "Indlæser i buffer",
        "plugin.cast-sender.state.playing" to "Afspiller på {device}",
        "plugin.cast-sender.state.paused" to "Sat på pause på {device}",
    )

    private fun DE(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Streaming ist auf diesem Gerät nicht verfügbar.",
        "plugin.cast-sender.connecting" to "Verbindung mit {device} wird hergestellt…",
        "plugin.cast-sender.connected" to "Streaming an {device}",
        "plugin.cast-sender.disconnected" to "Verbindung zu {device} getrennt",
        "plugin.cast-sender.error.session-failed" to "Die Cast-Sitzung konnte nicht gestartet werden.",
        "plugin.cast-sender.error.load-failed" to "Das Cast-Gerät hat die Medien abgelehnt.",
        "plugin.cast-sender.error.generic" to "Ein Cast-Fehler ist aufgetreten.",
        "plugin.cast-sender.action.connect" to "Übertragen",
        "plugin.cast-sender.action.disconnect" to "Cast beenden",
        "plugin.cast-sender.state.buffering" to "Puffern",
        "plugin.cast-sender.state.playing" to "Wiedergabe auf {device}",
        "plugin.cast-sender.state.paused" to "Pausiert auf {device}",
    )

    private fun EL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Η μετάδοση δεν είναι διαθέσιμη σε αυτή τη συσκευή.",
        "plugin.cast-sender.connecting" to "Σύνδεση με {device}…",
        "plugin.cast-sender.connected" to "Μετάδοση σε {device}",
        "plugin.cast-sender.disconnected" to "Αποσυνδέθηκε από {device}",
        "plugin.cast-sender.error.session-failed" to "Δεν ήταν δυνατή η έναρξη της μετάδοσης.",
        "plugin.cast-sender.error.load-failed" to "Η συσκευή μετάδοσης απέρριψε το πολυμέσο.",
        "plugin.cast-sender.error.generic" to "Παρουσιάστηκε σφάλμα μετάδοσης.",
        "plugin.cast-sender.action.connect" to "Προβολή σε τηλεόραση",
        "plugin.cast-sender.action.disconnect" to "Διακοπή μετάδοσης",
        "plugin.cast-sender.state.buffering" to "Αποθήκευση στη μνήμη",
        "plugin.cast-sender.state.playing" to "Αναπαραγωγή σε {device}",
        "plugin.cast-sender.state.paused" to "Σε παύση στο {device}",
    )

    private fun EN(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting is not available on this device.",
        "plugin.cast-sender.connecting" to "Connecting to {device}…",
        "plugin.cast-sender.connected" to "Casting to {device}",
        "plugin.cast-sender.disconnected" to "Disconnected from {device}",
        "plugin.cast-sender.error.session-failed" to "Could not start the cast session.",
        "plugin.cast-sender.error.load-failed" to "The cast device refused the media.",
        "plugin.cast-sender.error.generic" to "A cast error occurred.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Stop casting",
        "plugin.cast-sender.state.buffering" to "Buffering…",
        "plugin.cast-sender.state.playing" to "Playing on {device}",
        "plugin.cast-sender.state.paused" to "Paused on {device}",
    )

    private fun ES(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "El envío no está disponible en este dispositivo.",
        "plugin.cast-sender.connecting" to "Conectando con {device}…",
        "plugin.cast-sender.connected" to "Enviando a {device}",
        "plugin.cast-sender.disconnected" to "Desconectado de {device}",
        "plugin.cast-sender.error.session-failed" to "No se pudo iniciar la sesión de transmisión.",
        "plugin.cast-sender.error.load-failed" to "El dispositivo de transmisión rechazó el contenido.",
        "plugin.cast-sender.error.generic" to "Se produjo un error de transmisión.",
        "plugin.cast-sender.action.connect" to "Transmitir",
        "plugin.cast-sender.action.disconnect" to "Detener transmisión",
        "plugin.cast-sender.state.buffering" to "Cargando búfer",
        "plugin.cast-sender.state.playing" to "Reproduciendo en {device}",
        "plugin.cast-sender.state.paused" to "En pausa en {device}",
    )

    private fun ET(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Ülekanne pole selles seadmes saadaval.",
        "plugin.cast-sender.connecting" to "Ühendamine seadmega {device}…",
        "plugin.cast-sender.connected" to "Ülekanne seadmesse {device}",
        "plugin.cast-sender.disconnected" to "Ühendus seadmega {device} katkestatud",
        "plugin.cast-sender.error.session-failed" to "Ülekandeseanssi ei õnnestunud käivitada.",
        "plugin.cast-sender.error.load-failed" to "Ülekandeseade keeldus meediumi vastu võtmast.",
        "plugin.cast-sender.error.generic" to "Tekkis ülekandeviga.",
        "plugin.cast-sender.action.connect" to "Ülekanne",
        "plugin.cast-sender.action.disconnect" to "Peata ülekanne",
        "plugin.cast-sender.state.buffering" to "Puhverdamine",
        "plugin.cast-sender.state.playing" to "Esitatakse seadmes {device}",
        "plugin.cast-sender.state.paused" to "Peatatud seadmes {device}",
    )

    private fun EU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Igorpena ez dago erabilgarri gailu honetan.",
        "plugin.cast-sender.connecting" to "{device}(e)ra konektatzen…",
        "plugin.cast-sender.connected" to "{device}(e)ra igortzen",
        "plugin.cast-sender.disconnected" to "{device} gailutik deskonektatuta",
        "plugin.cast-sender.error.session-failed" to "Ezin izan da igorpen-saioa hasi.",
        "plugin.cast-sender.error.load-failed" to "Igorpen-gailuak multimedia errefusatu du.",
        "plugin.cast-sender.error.generic" to "Igorpen-errore bat gertatu da.",
        "plugin.cast-sender.action.connect" to "Igorri",
        "plugin.cast-sender.action.disconnect" to "Gelditu igorpena",
        "plugin.cast-sender.state.buffering" to "Bufferra kargatzen",
        "plugin.cast-sender.state.playing" to "{device} gailuan erreproduzitzen",
        "plugin.cast-sender.state.paused" to "{device} gailuan pausatuta",
    )

    private fun FA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ارسال در این دستگاه در دسترس نیست.",
        "plugin.cast-sender.connecting" to "در حال اتصال به {device}…",
        "plugin.cast-sender.connected" to "در حال ارسال به {device}",
        "plugin.cast-sender.disconnected" to "ارتباط با {device} قطع شد",
        "plugin.cast-sender.error.session-failed" to "نمی‌توان جلسهٔ پخش را آغاز کرد.",
        "plugin.cast-sender.error.load-failed" to "دستگاه پخش رسانه را رد کرد.",
        "plugin.cast-sender.error.generic" to "خطایی در پخش رخ داد.",
        "plugin.cast-sender.action.connect" to "ارسال به دستگاه",
        "plugin.cast-sender.action.disconnect" to "توقف پخش",
        "plugin.cast-sender.state.buffering" to "بارگذاری بافر",
        "plugin.cast-sender.state.playing" to "در حال پخش روی {device}",
        "plugin.cast-sender.state.paused" to "متوقف‌شده روی {device}",
    )

    private fun FI(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Lähetys ei ole käytettävissä tällä laitteella.",
        "plugin.cast-sender.connecting" to "Yhdistetään laitteeseen {device}…",
        "plugin.cast-sender.connected" to "Lähetetään laitteeseen {device}",
        "plugin.cast-sender.disconnected" to "Yhteys laitteeseen {device} katkaistu",
        "plugin.cast-sender.error.session-failed" to "Suoratoistoistuntoa ei voitu aloittaa.",
        "plugin.cast-sender.error.load-failed" to "Suoratoistolaite hylkäsi median.",
        "plugin.cast-sender.error.generic" to "Tapahtui suoratoistovirhe.",
        "plugin.cast-sender.action.connect" to "Toista laitteella",
        "plugin.cast-sender.action.disconnect" to "Lopeta suoratoisto",
        "plugin.cast-sender.state.buffering" to "Puskuroidaan",
        "plugin.cast-sender.state.playing" to "Toistetaan laitteella {device}",
        "plugin.cast-sender.state.paused" to "Keskeytetty laitteella {device}",
    )

    private fun FR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "La diffusion n\\'est pas disponible sur cet appareil.",
        "plugin.cast-sender.connecting" to "Connexion à {device}…",
        "plugin.cast-sender.connected" to "Diffusion vers {device}",
        "plugin.cast-sender.disconnected" to "Déconnecté de {device}",
        "plugin.cast-sender.error.session-failed" to "Impossible de démarrer la session de diffusion.",
        "plugin.cast-sender.error.load-failed" to "L\\'appareil de diffusion a refusé le média.",
        "plugin.cast-sender.error.generic" to "Une erreur de diffusion s\\'est produite.",
        "plugin.cast-sender.action.connect" to "Diffusion",
        "plugin.cast-sender.action.disconnect" to "Arrêter la diffusion",
        "plugin.cast-sender.state.buffering" to "Mise en mémoire tampon",
        "plugin.cast-sender.state.playing" to "Lecture sur {device}",
        "plugin.cast-sender.state.paused" to "En pause sur {device}",
    )

    private fun GA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Níl caitheamh ar fáil ar an ngléas seo.",
        "plugin.cast-sender.connecting" to "Ag nascadh le {device}…",
        "plugin.cast-sender.connected" to "Á chaitheamh chuig {device}",
        "plugin.cast-sender.disconnected" to "Dícheangailte ó {device}",
        "plugin.cast-sender.error.session-failed" to "Níorbh fhéidir an seisiún teilgean a thosú.",
        "plugin.cast-sender.error.load-failed" to "Dhiúltaigh an gléas teilgean don mheán.",
        "plugin.cast-sender.error.generic" to "Tharla earráid teilgean.",
        "plugin.cast-sender.action.connect" to "Teilg",
        "plugin.cast-sender.action.disconnect" to "Stop teilgean",
        "plugin.cast-sender.state.buffering" to "Ag maolánú",
        "plugin.cast-sender.state.playing" to "Á sheinm ar {device}",
        "plugin.cast-sender.state.paused" to "Ar sos ar {device}",
    )

    private fun GL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "A emisión non está dispoñible neste dispositivo.",
        "plugin.cast-sender.connecting" to "Conectando con {device}…",
        "plugin.cast-sender.connected" to "Emitindo a {device}",
        "plugin.cast-sender.disconnected" to "Desconectado de {device}",
        "plugin.cast-sender.error.session-failed" to "Non se puido iniciar a sesión de emisión.",
        "plugin.cast-sender.error.load-failed" to "O dispositivo de emisión rexeitou o contido.",
        "plugin.cast-sender.error.generic" to "Produciuse un erro de emisión.",
        "plugin.cast-sender.action.connect" to "Transmitir",
        "plugin.cast-sender.action.disconnect" to "Deter a emisión",
        "plugin.cast-sender.state.buffering" to "Cargando búfer",
        "plugin.cast-sender.state.playing" to "Reproducindo en {device}",
        "plugin.cast-sender.state.paused" to "En pausa en {device}",
    )

    private fun GU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "આ ઉપકરણ પર કાસ્ટિંગ ઉપલબ્ધ નથી.",
        "plugin.cast-sender.connecting" to "{device} સાથે કનેક્ટ થઈ રહ્યું છે…",
        "plugin.cast-sender.connected" to "{device} પર કાસ્ટ થઈ રહ્યું છે",
        "plugin.cast-sender.disconnected" to "{device} થી જોડાણ તૂટી ગયું",
        "plugin.cast-sender.error.session-failed" to "કાસ્ટ સત્ર શરૂ કરી શકાયું નહીં.",
        "plugin.cast-sender.error.load-failed" to "કાસ્ટ ઉપકરણે મીડિયા નકારી દીધું.",
        "plugin.cast-sender.error.generic" to "કાસ્ટ ભૂલ આવી.",
        "plugin.cast-sender.action.connect" to "કાસ્ટ",
        "plugin.cast-sender.action.disconnect" to "કાસ્ટ કરવાનું બંધ કરો",
        "plugin.cast-sender.state.buffering" to "બફરિંગ",
        "plugin.cast-sender.state.playing" to "{device} પર ચાલી રહ્યું છે",
        "plugin.cast-sender.state.paused" to "{device} પર થોભાવ્યું",
    )

    private fun HE(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "העברה אינה זמינה במכשיר זה.",
        "plugin.cast-sender.connecting" to "מתחבר אל {device}…",
        "plugin.cast-sender.connected" to "מעביר אל {device}",
        "plugin.cast-sender.disconnected" to "החיבור אל {device} נותק",
        "plugin.cast-sender.error.session-failed" to "לא ניתן היה להתחיל את הפעלת ההזרמה.",
        "plugin.cast-sender.error.load-failed" to "מכשיר ההזרמה דחה את המדיה.",
        "plugin.cast-sender.error.generic" to "אירעה שגיאת הזרמה.",
        "plugin.cast-sender.action.connect" to "שידור",
        "plugin.cast-sender.action.disconnect" to "הפסקת ההזרמה",
        "plugin.cast-sender.state.buffering" to "טוען למאגר",
        "plugin.cast-sender.state.playing" to "מתנגן ב-{device}",
        "plugin.cast-sender.state.paused" to "מושהה ב-{device}",
    )

    private fun HI(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "इस डिवाइस पर कास्टिंग उपलब्ध नहीं है।",
        "plugin.cast-sender.connecting" to "{device} से कनेक्ट हो रहा है…",
        "plugin.cast-sender.connected" to "{device} पर कास्ट हो रहा है",
        "plugin.cast-sender.disconnected" to "{device} से कनेक्शन टूट गया",
        "plugin.cast-sender.error.session-failed" to "कास्ट सत्र शुरू नहीं किया जा सका।",
        "plugin.cast-sender.error.load-failed" to "कास्ट डिवाइस ने मीडिया अस्वीकार कर दिया।",
        "plugin.cast-sender.error.generic" to "एक कास्ट त्रुटि हुई।",
        "plugin.cast-sender.action.connect" to "कास्ट",
        "plugin.cast-sender.action.disconnect" to "कास्ट करना रोकें",
        "plugin.cast-sender.state.buffering" to "बफ़रिंग",
        "plugin.cast-sender.state.playing" to "{device} पर चल रहा है",
        "plugin.cast-sender.state.paused" to "{device} पर रोका गया",
    )

    private fun HR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Emitiranje nije dostupno na ovom uređaju.",
        "plugin.cast-sender.connecting" to "Povezivanje s {device}…",
        "plugin.cast-sender.connected" to "Emitiranje na {device}",
        "plugin.cast-sender.disconnected" to "Prekinuta veza s {device}",
        "plugin.cast-sender.error.session-failed" to "Nije moguće pokrenuti sesiju emitiranja.",
        "plugin.cast-sender.error.load-failed" to "Uređaj za emitiranje odbio je medij.",
        "plugin.cast-sender.error.generic" to "Došlo je do pogreške emitiranja.",
        "plugin.cast-sender.action.connect" to "Emitiranje",
        "plugin.cast-sender.action.disconnect" to "Zaustavi emitiranje",
        "plugin.cast-sender.state.buffering" to "Spremanje u međuspremnik",
        "plugin.cast-sender.state.playing" to "Reproducira se na {device}",
        "plugin.cast-sender.state.paused" to "Pauzirano na {device}",
    )

    private fun HU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Az átküldés nem érhető el ezen az eszközön.",
        "plugin.cast-sender.connecting" to "Csatlakozás a következőhöz: {device}…",
        "plugin.cast-sender.connected" to "Átküldés a következőre: {device}",
        "plugin.cast-sender.disconnected" to "Lecsatlakozva a következőről: {device}",
        "plugin.cast-sender.error.session-failed" to "A casttelés nem indítható el.",
        "plugin.cast-sender.error.load-failed" to "A casteszköz elutasította a médiát.",
        "plugin.cast-sender.error.generic" to "Casthiba történt.",
        "plugin.cast-sender.action.connect" to "Közvetítés",
        "plugin.cast-sender.action.disconnect" to "Castelés leállítása",
        "plugin.cast-sender.state.buffering" to "Pufferelés",
        "plugin.cast-sender.state.playing" to "Lejátszás itt: {device}",
        "plugin.cast-sender.state.paused" to "Szüneteltetve itt: {device}",
    )

    private fun HY(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Հեռարձակումը հասանելի չէ այս սարքում:",
        "plugin.cast-sender.connecting" to "Միացում {device}-ին…",
        "plugin.cast-sender.connected" to "Հեռարձակում {device}-ին",
        "plugin.cast-sender.disconnected" to "{device}-ից անջատվել է",
        "plugin.cast-sender.error.session-failed" to "Չհաջողվեց սկսել հեռարձակման սեանսը։",
        "plugin.cast-sender.error.load-failed" to "Հեռարձակման սարքը մերժեց մեդիան։",
        "plugin.cast-sender.error.generic" to "Տեղի ունեցավ հեռարձակման սխալ։",
        "plugin.cast-sender.action.connect" to "Հերարացել",
        "plugin.cast-sender.action.disconnect" to "Դադարեցնել հեռարձակումը",
        "plugin.cast-sender.state.buffering" to "Բաֆերացում",
        "plugin.cast-sender.state.playing" to "Նվագարկվում է {device}-ում",
        "plugin.cast-sender.state.paused" to "Դադարեցված է {device}-ում",
    )

    private fun ID(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Transmisi tidak tersedia di perangkat ini.",
        "plugin.cast-sender.connecting" to "Menghubungkan ke {device}…",
        "plugin.cast-sender.connected" to "Mentransmisikan ke {device}",
        "plugin.cast-sender.disconnected" to "Terputus dari {device}",
        "plugin.cast-sender.error.session-failed" to "Tidak dapat memulai sesi cast.",
        "plugin.cast-sender.error.load-failed" to "Perangkat cast menolak media.",
        "plugin.cast-sender.error.generic" to "Terjadi kesalahan cast.",
        "plugin.cast-sender.action.connect" to "Transmisikan",
        "plugin.cast-sender.action.disconnect" to "Hentikan cast",
        "plugin.cast-sender.state.buffering" to "Memuat buffer",
        "plugin.cast-sender.state.playing" to "Memutar di {device}",
        "plugin.cast-sender.state.paused" to "Dijeda di {device}",
    )

    private fun IS(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Sending er ekki í boði á þessu tæki.",
        "plugin.cast-sender.connecting" to "Tengist við {device}…",
        "plugin.cast-sender.connected" to "Sendir til {device}",
        "plugin.cast-sender.disconnected" to "Aftengt frá {device}",
        "plugin.cast-sender.error.session-failed" to "Ekki tókst að hefja útsendingu.",
        "plugin.cast-sender.error.load-failed" to "Útsendingartækið hafnaði efninu.",
        "plugin.cast-sender.error.generic" to "Útsendingarvilla kom upp.",
        "plugin.cast-sender.action.connect" to "Senda á skjá",
        "plugin.cast-sender.action.disconnect" to "Stöðva útsendingu",
        "plugin.cast-sender.state.buffering" to "Hleður í biðminni",
        "plugin.cast-sender.state.playing" to "Spilar á {device}",
        "plugin.cast-sender.state.paused" to "Í hléi á {device}",
    )

    private fun IT(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "La trasmissione non è disponibile su questo dispositivo.",
        "plugin.cast-sender.connecting" to "Connessione a {device}…",
        "plugin.cast-sender.connected" to "Trasmissione su {device}",
        "plugin.cast-sender.disconnected" to "Disconnesso da {device}",
        "plugin.cast-sender.error.session-failed" to "Impossibile avviare la sessione di trasmissione.",
        "plugin.cast-sender.error.load-failed" to "Il dispositivo di trasmissione ha rifiutato il contenuto.",
        "plugin.cast-sender.error.generic" to "Si è verificato un errore di trasmissione.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Interrompi trasmissione",
        "plugin.cast-sender.state.buffering" to "Buffering",
        "plugin.cast-sender.state.playing" to "In riproduzione su {device}",
        "plugin.cast-sender.state.paused" to "In pausa su {device}",
    )

    private fun JA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "このデバイスではキャストを利用できません。",
        "plugin.cast-sender.connecting" to "{device} に接続中…",
        "plugin.cast-sender.connected" to "{device} にキャスト中",
        "plugin.cast-sender.disconnected" to "{device} から切断されました",
        "plugin.cast-sender.error.session-failed" to "キャストセッションを開始できませんでした。",
        "plugin.cast-sender.error.load-failed" to "キャストデバイスがメディアを拒否しました。",
        "plugin.cast-sender.error.generic" to "キャストエラーが発生しました。",
        "plugin.cast-sender.action.connect" to "キャスト",
        "plugin.cast-sender.action.disconnect" to "キャストを停止",
        "plugin.cast-sender.state.buffering" to "バッファリング中",
        "plugin.cast-sender.state.playing" to "{device} で再生中",
        "plugin.cast-sender.state.paused" to "{device} で一時停止中",
    )

    private fun KA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ტრანსლაცია ამ მოწყობილობაზე მიუწვდომელია.",
        "plugin.cast-sender.connecting" to "{device}-თან დაკავშირება…",
        "plugin.cast-sender.connected" to "ტრანსლაცია {device}-ზე",
        "plugin.cast-sender.disconnected" to "{device}-დან გათიშულია",
        "plugin.cast-sender.error.session-failed" to "ტრანსლაციის სესიის დაწყება ვერ მოხერხდა.",
        "plugin.cast-sender.error.load-failed" to "ტრანსლაციის მოწყობილობამ უარყო მედია.",
        "plugin.cast-sender.error.generic" to "მოხდა ტრანსლაციის შეცდომა.",
        "plugin.cast-sender.action.connect" to "გადაცემა",
        "plugin.cast-sender.action.disconnect" to "ტრანსლაციის შეჩერება",
        "plugin.cast-sender.state.buffering" to "ბუფერიზაცია",
        "plugin.cast-sender.state.playing" to "უკრავს {device}-ზე",
        "plugin.cast-sender.state.paused" to "შეჩერებულია {device}-ზე",
    )

    private fun KK(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Бұл құрылғыда тарату қолжетімсіз.",
        "plugin.cast-sender.connecting" to "{device} құрылғысына қосылуда…",
        "plugin.cast-sender.connected" to "{device} құрылғысына таратылуда",
        "plugin.cast-sender.disconnected" to "{device} құрылғысынан ажыратылды",
        "plugin.cast-sender.error.session-failed" to "Тарату сеансын бастау мүмкін болмады.",
        "plugin.cast-sender.error.load-failed" to "Тарату құрылғысы медиадан бас тартты.",
        "plugin.cast-sender.error.generic" to "Тарату қатесі орын алды.",
        "plugin.cast-sender.action.connect" to "Трансляциялау",
        "plugin.cast-sender.action.disconnect" to "Таратуды тоқтату",
        "plugin.cast-sender.state.buffering" to "Буферлеу",
        "plugin.cast-sender.state.playing" to "{device} құрылғысында ойнатылуда",
        "plugin.cast-sender.state.paused" to "{device} құрылғысында кідіртілген",
    )

    private fun KM(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ការថតមិនមាននៅលើឧបករណ៍នេះទេ។",
        "plugin.cast-sender.connecting" to "កំពុងភ្ជាប់ទៅ {device}…",
        "plugin.cast-sender.connected" to "កំពុងថតទៅ {device}",
        "plugin.cast-sender.disconnected" to "បានផ្ដាច់ពី {device}",
        "plugin.cast-sender.error.session-failed" to "មិនអាចចាប់ផ្ដើមវគ្គបញ្ជូនបានទេ។",
        "plugin.cast-sender.error.load-failed" to "ឧបករណ៍បញ្ជូនបានបដិសេធមេឌៀ។",
        "plugin.cast-sender.error.generic" to "មានកំហុសក្នុងការបញ្ជូន។",
        "plugin.cast-sender.action.connect" to "ខាស",
        "plugin.cast-sender.action.disconnect" to "បញ្ឈប់ការបញ្ជូន",
        "plugin.cast-sender.state.buffering" to "កំពុងផ្ទុក",
        "plugin.cast-sender.state.playing" to "កំពុងចាក់នៅលើ {device}",
        "plugin.cast-sender.state.paused" to "ផ្អាកនៅលើ {device}",
    )

    private fun KN(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ಈ ಸಾಧನದಲ್ಲಿ ಕಾಸ್ಟಿಂಗ್ ಲಭ್ಯವಿಲ್ಲ.",
        "plugin.cast-sender.connecting" to "{device} ಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…",
        "plugin.cast-sender.connected" to "{device} ಗೆ ಕಾಸ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
        "plugin.cast-sender.disconnected" to "{device} ನಿಂದ ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ",
        "plugin.cast-sender.error.session-failed" to "ಕಾಸ್ಟ್ ಅವಧಿಯನ್ನು ಪ್ರಾರಂಭಿಸಲಾಗಲಿಲ್ಲ.",
        "plugin.cast-sender.error.load-failed" to "ಕಾಸ್ಟ್ ಸಾಧನವು ಮಾಧ್ಯಮವನ್ನು ನಿರಾಕರಿಸಿತು.",
        "plugin.cast-sender.error.generic" to "ಕಾಸ್ಟ್ ದೋಷ ಸಂಭವಿಸಿದೆ.",
        "plugin.cast-sender.action.connect" to "ಕಾಸ್ಟ್",
        "plugin.cast-sender.action.disconnect" to "ಕಾಸ್ಟ್ ನಿಲ್ಲಿಸಿ",
        "plugin.cast-sender.state.buffering" to "ಬಫರಿಂಗ್",
        "plugin.cast-sender.state.playing" to "{device} ನಲ್ಲಿ ಪ್ಲೇ ಆಗುತ್ತಿದೆ",
        "plugin.cast-sender.state.paused" to "{device} ನಲ್ಲಿ ವಿರಾಮಗೊಂಡಿದೆ",
    )

    private fun KO(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "이 기기에서는 캐스트를 사용할 수 없습니다.",
        "plugin.cast-sender.connecting" to "{device}에 연결 중…",
        "plugin.cast-sender.connected" to "{device}에 캐스트 중",
        "plugin.cast-sender.disconnected" to "{device}에서 연결이 끊어졌습니다",
        "plugin.cast-sender.error.session-failed" to "캐스트 세션을 시작할 수 없습니다.",
        "plugin.cast-sender.error.load-failed" to "캐스트 기기가 미디어를 거부했습니다.",
        "plugin.cast-sender.error.generic" to "캐스트 오류가 발생했습니다.",
        "plugin.cast-sender.action.connect" to "캐스트",
        "plugin.cast-sender.action.disconnect" to "캐스트 중지",
        "plugin.cast-sender.state.buffering" to "버퍼링",
        "plugin.cast-sender.state.playing" to "{device}에서 재생 중",
        "plugin.cast-sender.state.paused" to "{device}에서 일시정지됨",
    )

    private fun KU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Weşandin li ser vê amûrê tune.",
        "plugin.cast-sender.connecting" to "Bi {device} ve girêdan…",
        "plugin.cast-sender.connected" to "Li {device} tê weşandin",
        "plugin.cast-sender.disconnected" to "Ji {device} qut bû",
        "plugin.cast-sender.error.session-failed" to "Danişîna weşandinê dest pê nekir.",
        "plugin.cast-sender.error.load-failed" to "Amûra weşandinê medya red kir.",
        "plugin.cast-sender.error.generic" to "Çewtiyeke weşandinê çêbû.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Weşandinê rawestîne",
        "plugin.cast-sender.state.buffering" to "Barkirin",
        "plugin.cast-sender.state.playing" to "Li ser {device} tê lêdan",
        "plugin.cast-sender.state.paused" to "Li ser {device} hate rawestandin",
    )

    private fun KY(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Бул түзмөктө таратуу жеткиликсиз.",
        "plugin.cast-sender.connecting" to "{device} түзмөгүнө туташууда…",
        "plugin.cast-sender.connected" to "{device} түзмөгүнө таратылууда",
        "plugin.cast-sender.disconnected" to "{device} түзмөгүнөн ажыратылды",
        "plugin.cast-sender.error.session-failed" to "Тарату сеансын баштоо мүмкүн болгон жок.",
        "plugin.cast-sender.error.load-failed" to "Тарату түзмөгү медианы четке какты.",
        "plugin.cast-sender.error.generic" to "Тарату катасы пайда болду.",
        "plugin.cast-sender.action.connect" to "Трансляциялоо",
        "plugin.cast-sender.action.disconnect" to "Таратууну токтотуу",
        "plugin.cast-sender.state.buffering" to "Буферлөө",
        "plugin.cast-sender.state.playing" to "{device} түзмөгүндө ойнотулууда",
        "plugin.cast-sender.state.paused" to "{device} түзмөгүндө тындырылды",
    )

    private fun LO(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ການສົ່ງບໍ່ມີຢູ່ໃນອຸປະກອນນີ້.",
        "plugin.cast-sender.connecting" to "ກຳລັງເຊື່ອມຕໍ່ກັບ {device}…",
        "plugin.cast-sender.connected" to "ກຳລັງສົ່ງໄປຍັງ {device}",
        "plugin.cast-sender.disconnected" to "ຕັດການເຊື່ອມຕໍ່ຈາກ {device}",
        "plugin.cast-sender.error.session-failed" to "ບໍ່ສາມາດເລີ່ມເຊດຊັນການສົ່ງສັນຍານໄດ້.",
        "plugin.cast-sender.error.load-failed" to "ອຸປະກອນສົ່ງສັນຍານໄດ້ປະຕິເສດສື່.",
        "plugin.cast-sender.error.generic" to "ເກີດຂໍ້ຜິດພາດໃນການສົ່ງສັນຍານ.",
        "plugin.cast-sender.action.connect" to "ສົ່ງຫາໜ້າຈໍ",
        "plugin.cast-sender.action.disconnect" to "ຢຸດການສົ່ງສັນຍານ",
        "plugin.cast-sender.state.buffering" to "ກຳລັງໂຫຼດ",
        "plugin.cast-sender.state.playing" to "ກຳລັງຫຼິ້ນຢູ່ {device}",
        "plugin.cast-sender.state.paused" to "ຢຸດຊົ່ວຄາວຢູ່ {device}",
    )

    private fun LT(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Perdavimas šiame įrenginyje nepasiekiamas.",
        "plugin.cast-sender.connecting" to "Jungiamasi prie {device}…",
        "plugin.cast-sender.connected" to "Perduodama į {device}",
        "plugin.cast-sender.disconnected" to "Atjungta nuo {device}",
        "plugin.cast-sender.error.session-failed" to "Nepavyko pradėti perdavimo seanso.",
        "plugin.cast-sender.error.load-failed" to "Perdavimo įrenginys atmetė mediją.",
        "plugin.cast-sender.error.generic" to "Įvyko perdavimo klaida.",
        "plugin.cast-sender.action.connect" to "Transliuoti",
        "plugin.cast-sender.action.disconnect" to "Stabdyti perdavimą",
        "plugin.cast-sender.state.buffering" to "Buferizuojama",
        "plugin.cast-sender.state.playing" to "Atkuriama įrenginyje {device}",
        "plugin.cast-sender.state.paused" to "Pristabdyta įrenginyje {device}",
    )

    private fun LV(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Apraide šajā ierīcē nav pieejama.",
        "plugin.cast-sender.connecting" to "Notiek savienojums ar {device}…",
        "plugin.cast-sender.connected" to "Tiek apraidīts uz {device}",
        "plugin.cast-sender.disconnected" to "Atvienots no {device}",
        "plugin.cast-sender.error.session-failed" to "Neizdevās sākt apraides sesiju.",
        "plugin.cast-sender.error.load-failed" to "Apraides ierīce noraidīja saturu.",
        "plugin.cast-sender.error.generic" to "Radās apraides kļūda.",
        "plugin.cast-sender.action.connect" to "Straumēt uz ierīci",
        "plugin.cast-sender.action.disconnect" to "Apturēt apraidi",
        "plugin.cast-sender.state.buffering" to "Buferizēšana",
        "plugin.cast-sender.state.playing" to "Atskaņo ierīcē {device}",
        "plugin.cast-sender.state.paused" to "Pauzēts ierīcē {device}",
    )

    private fun MK(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Емитувањето не е достапно на овој уред.",
        "plugin.cast-sender.connecting" to "Поврзување со {device}…",
        "plugin.cast-sender.connected" to "Се емитува на {device}",
        "plugin.cast-sender.disconnected" to "Прекината врска со {device}",
        "plugin.cast-sender.error.session-failed" to "Сесијата за пренос не можеше да започне.",
        "plugin.cast-sender.error.load-failed" to "Уредот за пренос го одби медиумот.",
        "plugin.cast-sender.error.generic" to "Се појави грешка при пренос.",
        "plugin.cast-sender.action.connect" to "Емитувај",
        "plugin.cast-sender.action.disconnect" to "Запри пренос",
        "plugin.cast-sender.state.buffering" to "Баферирање",
        "plugin.cast-sender.state.playing" to "Се репродуцира на {device}",
        "plugin.cast-sender.state.paused" to "Паузирано на {device}",
    )

    private fun ML(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ഈ ഉപകരണത്തിൽ കാസ്റ്റിംഗ് ലഭ്യമല്ല.",
        "plugin.cast-sender.connecting" to "{device} ലേക്ക് കണക്റ്റ് ചെയ്യുന്നു…",
        "plugin.cast-sender.connected" to "{device} ലേക്ക് കാസ്റ്റ് ചെയ്യുന്നു",
        "plugin.cast-sender.disconnected" to "{device} എന്നതിൽ നിന്ന് വിച്ഛേദിച്ചു",
        "plugin.cast-sender.error.session-failed" to "കാസ്റ്റ് സെഷൻ ആരംഭിക്കാനായില്ല.",
        "plugin.cast-sender.error.load-failed" to "കാസ്റ്റ് ഉപകരണം മീഡിയ നിരസിച്ചു.",
        "plugin.cast-sender.error.generic" to "ഒരു കാസ്റ്റ് പിശക് സംഭവിച്ചു.",
        "plugin.cast-sender.action.connect" to "കാസ്റ്റ്",
        "plugin.cast-sender.action.disconnect" to "കാസ്റ്റ് ചെയ്യുന്നത് നിർത്തുക",
        "plugin.cast-sender.state.buffering" to "ബഫറിംഗ്",
        "plugin.cast-sender.state.playing" to "{device}-ൽ പ്ലേ ചെയ്യുന്നു",
        "plugin.cast-sender.state.paused" to "{device}-ൽ താൽക്കാലികമായി നിർത്തി",
    )

    private fun MN(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Энэ төхөөрөмж дээр дамжуулах боломжгүй.",
        "plugin.cast-sender.connecting" to "{device}-д холбогдож байна…",
        "plugin.cast-sender.connected" to "{device}-д дамжуулж байна",
        "plugin.cast-sender.disconnected" to "{device}-с салгагдсан",
        "plugin.cast-sender.error.session-failed" to "Дамжуулах сессийг эхлүүлж чадсангүй.",
        "plugin.cast-sender.error.load-failed" to "Дамжуулах төхөөрөмж медиаг татгалзлаа.",
        "plugin.cast-sender.error.generic" to "Дамжуулах алдаа гарлаа.",
        "plugin.cast-sender.action.connect" to "Дамжуулах",
        "plugin.cast-sender.action.disconnect" to "Дамжуулахыг зогсоох",
        "plugin.cast-sender.state.buffering" to "Ачааллаж байна",
        "plugin.cast-sender.state.playing" to "{device} дээр тоглуулж байна",
        "plugin.cast-sender.state.paused" to "{device} дээр түр зогсоосон",
    )

    private fun MR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "या डिव्हाइसवर कास्टिंग उपलब्ध नाही.",
        "plugin.cast-sender.connecting" to "{device} शी कनेक्ट होत आहे…",
        "plugin.cast-sender.connected" to "{device} वर कास्ट होत आहे",
        "plugin.cast-sender.disconnected" to "{device} पासून कनेक्शन तुटले",
        "plugin.cast-sender.error.session-failed" to "कास्ट सत्र सुरू करता आले नाही.",
        "plugin.cast-sender.error.load-failed" to "कास्ट उपकरणाने मीडिया नाकारला.",
        "plugin.cast-sender.error.generic" to "कास्ट त्रुटी आली.",
        "plugin.cast-sender.action.connect" to "कास्ट",
        "plugin.cast-sender.action.disconnect" to "कास्ट करणे थांबवा",
        "plugin.cast-sender.state.buffering" to "बफरिंग",
        "plugin.cast-sender.state.playing" to "{device} वर वाजत आहे",
        "plugin.cast-sender.state.paused" to "{device} वर थांबवले",
    )

    private fun MS(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Penghantaran tidak tersedia pada peranti ini.",
        "plugin.cast-sender.connecting" to "Menyambung ke {device}…",
        "plugin.cast-sender.connected" to "Menghantar ke {device}",
        "plugin.cast-sender.disconnected" to "Diputuskan daripada {device}",
        "plugin.cast-sender.error.session-failed" to "Tidak dapat memulakan sesi cast.",
        "plugin.cast-sender.error.load-failed" to "Peranti cast menolak media.",
        "plugin.cast-sender.error.generic" to "Ralat cast berlaku.",
        "plugin.cast-sender.action.connect" to "Hantar",
        "plugin.cast-sender.action.disconnect" to "Hentikan cast",
        "plugin.cast-sender.state.buffering" to "Penimbalan",
        "plugin.cast-sender.state.playing" to "Bermain di {device}",
        "plugin.cast-sender.state.paused" to "Dijeda di {device}",
    )

    private fun MY(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ဤစက်ပစ္စည်းတွင် Cast လုပ်၍မရပါ။",
        "plugin.cast-sender.connecting" to "{device} သို့ ချိတ်ဆက်နေသည်…",
        "plugin.cast-sender.connected" to "{device} သို့ Cast လုပ်နေသည်",
        "plugin.cast-sender.disconnected" to "{device} မှ ချိတ်ဆက်မှု ပြတ်တောက်သွားသည်",
        "plugin.cast-sender.error.session-failed" to "Cast session ကို စတင်၍မရပါ။",
        "plugin.cast-sender.error.load-failed" to "Cast စက်ပစ္စည်းက မီဒီယာကို ငြင်းပယ်လိုက်သည်။",
        "plugin.cast-sender.error.generic" to "Cast အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။",
        "plugin.cast-sender.action.connect" to "ထုတ်လွှင့်",
        "plugin.cast-sender.action.disconnect" to "Cast ရပ်ရန်",
        "plugin.cast-sender.state.buffering" to "ဘာဖာလုပ်နေသည်",
        "plugin.cast-sender.state.playing" to "{device} တွင် ဖွင့်နေသည်",
        "plugin.cast-sender.state.paused" to "{device} တွင် ခေတ္တရပ်ထားသည်",
    )

    private fun NB(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting er ikke tilgjengelig på denne enheten.",
        "plugin.cast-sender.connecting" to "Kobler til {device}…",
        "plugin.cast-sender.connected" to "Caster til {device}",
        "plugin.cast-sender.disconnected" to "Koblet fra {device}",
        "plugin.cast-sender.error.session-failed" to "Kunne ikke starte cast-økten.",
        "plugin.cast-sender.error.load-failed" to "Cast-enheten avviste mediet.",
        "plugin.cast-sender.error.generic" to "Det oppstod en cast-feil.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Stopp cast",
        "plugin.cast-sender.state.buffering" to "Laster inn",
        "plugin.cast-sender.state.playing" to "Spiller av på {device}",
        "plugin.cast-sender.state.paused" to "Satt på pause på {device}",
    )

    private fun NE(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "यस यन्त्रमा कास्टिङ उपलब्ध छैन।",
        "plugin.cast-sender.connecting" to "{device} सँग जडान हुँदै…",
        "plugin.cast-sender.connected" to "{device} मा कास्ट गर्दै",
        "plugin.cast-sender.disconnected" to "{device} बाट विच्छेद भयो",
        "plugin.cast-sender.error.session-failed" to "कास्ट सत्र सुरु गर्न सकिएन।",
        "plugin.cast-sender.error.load-failed" to "कास्ट उपकरणले मिडिया अस्वीकार गर्‍यो।",
        "plugin.cast-sender.error.generic" to "कास्ट त्रुटि भयो।",
        "plugin.cast-sender.action.connect" to "कास्ट",
        "plugin.cast-sender.action.disconnect" to "कास्ट रोक्नुहोस्",
        "plugin.cast-sender.state.buffering" to "बफरिङ",
        "plugin.cast-sender.state.playing" to "{device} मा प्ले हुँदै",
        "plugin.cast-sender.state.paused" to "{device} मा पज गरिएको",
    )

    private fun NL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casten is niet beschikbaar op dit apparaat.",
        "plugin.cast-sender.connecting" to "Verbinden met {device}…",
        "plugin.cast-sender.connected" to "Casten naar {device}",
        "plugin.cast-sender.disconnected" to "Verbinding met {device} verbroken",
        "plugin.cast-sender.error.session-failed" to "Cast-sessie kon niet worden gestart.",
        "plugin.cast-sender.error.load-failed" to "Het cast-apparaat weigerde de media.",
        "plugin.cast-sender.error.generic" to "Er is een castfout opgetreden.",
        "plugin.cast-sender.action.connect" to "Casten",
        "plugin.cast-sender.action.disconnect" to "Stop met casten",
        "plugin.cast-sender.state.buffering" to "Bufferen…",
        "plugin.cast-sender.state.playing" to "Speelt op {device}",
        "plugin.cast-sender.state.paused" to "Gepauzeerd op {device}",
    )

    private fun NN(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting er ikkje tilgjengeleg på denne eininga.",
        "plugin.cast-sender.connecting" to "Koplar til {device}…",
        "plugin.cast-sender.connected" to "Castar til {device}",
        "plugin.cast-sender.disconnected" to "Kopla frå {device}",
        "plugin.cast-sender.error.session-failed" to "Kunne ikkje starte cast-økta.",
        "plugin.cast-sender.error.load-failed" to "Cast-eininga avviste mediet.",
        "plugin.cast-sender.error.generic" to "Det oppstod ein cast-feil.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Stopp cast",
        "plugin.cast-sender.state.buffering" to "Lastar inn",
        "plugin.cast-sender.state.playing" to "Spelar av på {device}",
        "plugin.cast-sender.state.paused" to "Sett på pause på {device}",
    )

    private fun NO(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting er ikke tilgjengelig på denne enheten.",
        "plugin.cast-sender.connecting" to "Kobler til {device}…",
        "plugin.cast-sender.connected" to "Caster til {device}",
        "plugin.cast-sender.disconnected" to "Koblet fra {device}",
        "plugin.cast-sender.error.session-failed" to "Kunne ikke starte cast-økten.",
        "plugin.cast-sender.error.load-failed" to "Cast-enheten avviste mediet.",
        "plugin.cast-sender.error.generic" to "Det oppstod en cast-feil.",
        "plugin.cast-sender.action.connect" to "Cast",
        "plugin.cast-sender.action.disconnect" to "Stopp cast",
        "plugin.cast-sender.state.buffering" to "Laster inn",
        "plugin.cast-sender.state.playing" to "Spiller av på {device}",
        "plugin.cast-sender.state.paused" to "Satt på pause på {device}",
    )

    private fun OC(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "La difusion es pas disponibla sus aqueste aparelh.",
        "plugin.cast-sender.connecting" to "Connexion a {device}…",
        "plugin.cast-sender.connected" to "Difusion cap a {device}",
        "plugin.cast-sender.disconnected" to "Desconnectat de {device}",
        "plugin.cast-sender.error.session-failed" to "Impossible d\\'aviar la session de difusion.",
        "plugin.cast-sender.error.load-failed" to "L\\'aparelh de difusion a refusat lo mèdia.",
        "plugin.cast-sender.error.generic" to "Una error de difusion s\\'es producha.",
        "plugin.cast-sender.action.connect" to "Emetre",
        "plugin.cast-sender.action.disconnect" to "Arrestar la difusion",
        "plugin.cast-sender.state.buffering" to "Cargament",
        "plugin.cast-sender.state.playing" to "Lectura sus {device}",
        "plugin.cast-sender.state.paused" to "En pausa sus {device}",
    )

    private fun PA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ਇਸ ਡਿਵਾਈਸ \\'ਤੇ ਕਾਸਟਿੰਗ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
        "plugin.cast-sender.connecting" to "{device} ਨਾਲ ਕਨੈਕਟ ਹੋ ਰਿਹਾ ਹੈ…",
        "plugin.cast-sender.connected" to "{device} \\'ਤੇ ਕਾਸਟ ਹੋ ਰਿਹਾ ਹੈ",
        "plugin.cast-sender.disconnected" to "{device} ਤੋਂ ਕਨੈਕਸ਼ਨ ਟੁੱਟ ਗਿਆ",
        "plugin.cast-sender.error.session-failed" to "ਕਾਸਟ ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ।",
        "plugin.cast-sender.error.load-failed" to "ਕਾਸਟ ਡਿਵਾਈਸ ਨੇ ਮੀਡੀਆ ਅਸਵੀਕਾਰ ਕਰ ਦਿੱਤਾ।",
        "plugin.cast-sender.error.generic" to "ਇੱਕ ਕਾਸਟ ਗਲਤੀ ਆਈ।",
        "plugin.cast-sender.action.connect" to "ਕਾਸਟ",
        "plugin.cast-sender.action.disconnect" to "ਕਾਸਟ ਕਰਨਾ ਬੰਦ ਕਰੋ",
        "plugin.cast-sender.state.buffering" to "ਬਫਰਿੰਗ",
        "plugin.cast-sender.state.playing" to "{device} \\'ਤੇ ਚੱਲ ਰਿਹਾ ਹੈ",
        "plugin.cast-sender.state.paused" to "{device} \\'ਤੇ ਰੋਕਿਆ ਗਿਆ",
    )

    private fun PL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Przesyłanie nie jest dostępne na tym urządzeniu.",
        "plugin.cast-sender.connecting" to "Łączenie z {device}…",
        "plugin.cast-sender.connected" to "Przesyłanie do {device}",
        "plugin.cast-sender.disconnected" to "Rozłączono z {device}",
        "plugin.cast-sender.error.session-failed" to "Nie udało się rozpocząć sesji przesyłania.",
        "plugin.cast-sender.error.load-failed" to "Urządzenie do przesyłania odrzuciło multimedia.",
        "plugin.cast-sender.error.generic" to "Wystąpił błąd przesyłania.",
        "plugin.cast-sender.action.connect" to "Rzuć",
        "plugin.cast-sender.action.disconnect" to "Zatrzymaj przesyłanie",
        "plugin.cast-sender.state.buffering" to "Buforowanie",
        "plugin.cast-sender.state.playing" to "Odtwarzanie na {device}",
        "plugin.cast-sender.state.paused" to "Wstrzymano na {device}",
    )

    private fun PT(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "A transmissão não está disponível neste dispositivo.",
        "plugin.cast-sender.connecting" to "A ligar a {device}…",
        "plugin.cast-sender.connected" to "A transmitir para {device}",
        "plugin.cast-sender.disconnected" to "Desligado de {device}",
        "plugin.cast-sender.error.session-failed" to "Não foi possível iniciar a sessão de transmissão.",
        "plugin.cast-sender.error.load-failed" to "O dispositivo de transmissão recusou o conteúdo.",
        "plugin.cast-sender.error.generic" to "Ocorreu um erro de transmissão.",
        "plugin.cast-sender.action.connect" to "Transmitir",
        "plugin.cast-sender.action.disconnect" to "Parar transmissão",
        "plugin.cast-sender.state.buffering" to "A carregar",
        "plugin.cast-sender.state.playing" to "A reproduzir em {device}",
        "plugin.cast-sender.state.paused" to "Em pausa em {device}",
    )

    private fun PT_BR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "A transmissão não está disponível neste dispositivo.",
        "plugin.cast-sender.connecting" to "Conectando a {device}…",
        "plugin.cast-sender.connected" to "Transmitindo para {device}",
        "plugin.cast-sender.disconnected" to "Desconectado de {device}",
        "plugin.cast-sender.error.session-failed" to "Não foi possível iniciar a sessão de transmissão.",
        "plugin.cast-sender.error.load-failed" to "O dispositivo de transmissão recusou a mídia.",
        "plugin.cast-sender.error.generic" to "Ocorreu um erro de transmissão.",
        "plugin.cast-sender.action.connect" to "Transmitir",
        "plugin.cast-sender.action.disconnect" to "Parar transmissão",
        "plugin.cast-sender.state.buffering" to "Carregando",
        "plugin.cast-sender.state.playing" to "Reproduzindo em {device}",
        "plugin.cast-sender.state.paused" to "Pausado em {device}",
    )

    private fun RO(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Transmiterea nu este disponibilă pe acest dispozitiv.",
        "plugin.cast-sender.connecting" to "Se conectează la {device}…",
        "plugin.cast-sender.connected" to "Se transmite către {device}",
        "plugin.cast-sender.disconnected" to "Deconectat de la {device}",
        "plugin.cast-sender.error.session-failed" to "Sesiunea de difuzare nu a putut fi pornită.",
        "plugin.cast-sender.error.load-failed" to "Dispozitivul de difuzare a refuzat conținutul media.",
        "plugin.cast-sender.error.generic" to "A apărut o eroare de difuzare.",
        "plugin.cast-sender.action.connect" to "Redare",
        "plugin.cast-sender.action.disconnect" to "Oprește difuzarea",
        "plugin.cast-sender.state.buffering" to "Se încarcă",
        "plugin.cast-sender.state.playing" to "Se redă pe {device}",
        "plugin.cast-sender.state.paused" to "În pauză pe {device}",
    )

    private fun RU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Трансляция недоступна на этом устройстве.",
        "plugin.cast-sender.connecting" to "Подключение к {device}…",
        "plugin.cast-sender.connected" to "Трансляция на {device}",
        "plugin.cast-sender.disconnected" to "Отключено от {device}",
        "plugin.cast-sender.error.session-failed" to "Не удалось запустить сеанс трансляции.",
        "plugin.cast-sender.error.load-failed" to "Устройство трансляции отклонило медиафайл.",
        "plugin.cast-sender.error.generic" to "Произошла ошибка трансляции.",
        "plugin.cast-sender.action.connect" to "Трансляция",
        "plugin.cast-sender.action.disconnect" to "Остановить трансляцию",
        "plugin.cast-sender.state.buffering" to "Буферизация",
        "plugin.cast-sender.state.playing" to "Воспроизводится на {device}",
        "plugin.cast-sender.state.paused" to "Приостановлено на {device}",
    )

    private fun SI(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "මෙම උපාංගයේ විකාශනය ලබා ගත නොහැක.",
        "plugin.cast-sender.connecting" to "{device} වෙත සම්බන්ධ වෙමින්…",
        "plugin.cast-sender.connected" to "{device} වෙත විකාශනය වෙමින්",
        "plugin.cast-sender.disconnected" to "{device} වෙතින් විසන්ධි විය",
        "plugin.cast-sender.error.session-failed" to "කාස්ට් සැසිය ආරම්භ කළ නොහැකි විය.",
        "plugin.cast-sender.error.load-failed" to "කාස්ට් උපාංගය මාධ්‍ය ප්‍රතික්ෂේප කළේය.",
        "plugin.cast-sender.error.generic" to "කාස්ට් දෝෂයක් සිදු විය.",
        "plugin.cast-sender.action.connect" to "විකාශනය",
        "plugin.cast-sender.action.disconnect" to "කාස්ට් කිරීම නවත්වන්න",
        "plugin.cast-sender.state.buffering" to "බෆරනය",
        "plugin.cast-sender.state.playing" to "{device} මත වාදනය වෙමින්",
        "plugin.cast-sender.state.paused" to "{device} මත විරාම කර ඇත",
    )

    private fun SK(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Odosielanie nie je na tomto zariadení k dispozícii.",
        "plugin.cast-sender.connecting" to "Pripája sa k {device}…",
        "plugin.cast-sender.connected" to "Odosiela sa do {device}",
        "plugin.cast-sender.disconnected" to "Odpojené od {device}",
        "plugin.cast-sender.error.session-failed" to "Reláciu prenosu sa nepodarilo spustiť.",
        "plugin.cast-sender.error.load-failed" to "Zariadenie na prenos odmietlo médium.",
        "plugin.cast-sender.error.generic" to "Vyskytla sa chyba prenosu.",
        "plugin.cast-sender.action.connect" to "Prenášať",
        "plugin.cast-sender.action.disconnect" to "Zastaviť prenos",
        "plugin.cast-sender.state.buffering" to "Načítavanie",
        "plugin.cast-sender.state.playing" to "Prehráva sa na {device}",
        "plugin.cast-sender.state.paused" to "Pozastavené na {device}",
    )

    private fun SL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Predvajanje v tej napravi ni na voljo.",
        "plugin.cast-sender.connecting" to "Povezovanje z {device}…",
        "plugin.cast-sender.connected" to "Predvajanje na {device}",
        "plugin.cast-sender.disconnected" to "Prekinjena povezava z {device}",
        "plugin.cast-sender.error.session-failed" to "Seje predvajanja ni bilo mogoče začeti.",
        "plugin.cast-sender.error.load-failed" to "Naprava za predvajanje je zavrnila medij.",
        "plugin.cast-sender.error.generic" to "Prišlo je do napake pri predvajanju.",
        "plugin.cast-sender.action.connect" to "Predvajaj na TV",
        "plugin.cast-sender.action.disconnect" to "Ustavi predvajanje",
        "plugin.cast-sender.state.buffering" to "Medpomnjenje",
        "plugin.cast-sender.state.playing" to "Predvaja se na {device}",
        "plugin.cast-sender.state.paused" to "Zaustavljeno na {device}",
    )

    private fun SQ(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Transmetimi nuk është i disponueshëm në këtë pajisje.",
        "plugin.cast-sender.connecting" to "Po lidhet me {device}…",
        "plugin.cast-sender.connected" to "Po transmetohet te {device}",
        "plugin.cast-sender.disconnected" to "U shkëput nga {device}",
        "plugin.cast-sender.error.session-failed" to "Sesioni i transmetimit nuk mund të niste.",
        "plugin.cast-sender.error.load-failed" to "Pajisja e transmetimit e refuzoi median.",
        "plugin.cast-sender.error.generic" to "Ndodhi një gabim transmetimi.",
        "plugin.cast-sender.action.connect" to "Transmetim",
        "plugin.cast-sender.action.disconnect" to "Ndalo transmetimin",
        "plugin.cast-sender.state.buffering" to "Duke ngarkuar",
        "plugin.cast-sender.state.playing" to "Po luhet në {device}",
        "plugin.cast-sender.state.paused" to "Në pauzë në {device}",
    )

    private fun SR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Емитовање није доступно на овом уређају.",
        "plugin.cast-sender.connecting" to "Повезивање са {device}…",
        "plugin.cast-sender.connected" to "Емитовање на {device}",
        "plugin.cast-sender.disconnected" to "Веза са {device} је прекинута",
        "plugin.cast-sender.error.session-failed" to "Сесија преноса није могла да се покрене.",
        "plugin.cast-sender.error.load-failed" to "Уређај за пренос је одбио медиј.",
        "plugin.cast-sender.error.generic" to "Дошло је до грешке у преносу.",
        "plugin.cast-sender.action.connect" to "Емитовање",
        "plugin.cast-sender.action.disconnect" to "Заустави пренос",
        "plugin.cast-sender.state.buffering" to "Баферовање",
        "plugin.cast-sender.state.playing" to "Репродукује се на {device}",
        "plugin.cast-sender.state.paused" to "Паузирано на {device}",
    )

    private fun SV(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Casting är inte tillgängligt på den här enheten.",
        "plugin.cast-sender.connecting" to "Ansluter till {device}…",
        "plugin.cast-sender.connected" to "Castar till {device}",
        "plugin.cast-sender.disconnected" to "Frånkopplad från {device}",
        "plugin.cast-sender.error.session-failed" to "Det gick inte att starta castningssessionen.",
        "plugin.cast-sender.error.load-failed" to "Castningsenheten avvisade mediet.",
        "plugin.cast-sender.error.generic" to "Ett castningsfel inträffade.",
        "plugin.cast-sender.action.connect" to "Sändning",
        "plugin.cast-sender.action.disconnect" to "Stoppa castning",
        "plugin.cast-sender.state.buffering" to "Buffrar",
        "plugin.cast-sender.state.playing" to "Spelas upp på {device}",
        "plugin.cast-sender.state.paused" to "Pausad på {device}",
    )

    private fun SW(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Utumaji haupatikani kwenye kifaa hiki.",
        "plugin.cast-sender.connecting" to "Inaunganisha kwenye {device}…",
        "plugin.cast-sender.connected" to "Inatuma kwa {device}",
        "plugin.cast-sender.disconnected" to "Imekatwa kutoka {device}",
        "plugin.cast-sender.error.session-failed" to "Imeshindwa kuanzisha kipindi cha kutangaza.",
        "plugin.cast-sender.error.load-failed" to "Kifaa cha kutangaza kilikataa media.",
        "plugin.cast-sender.error.generic" to "Hitilafu ya kutangaza imetokea.",
        "plugin.cast-sender.action.connect" to "Tuma",
        "plugin.cast-sender.action.disconnect" to "Acha kutangaza",
        "plugin.cast-sender.state.buffering" to "Inapakia",
        "plugin.cast-sender.state.playing" to "Inacheza kwenye {device}",
        "plugin.cast-sender.state.paused" to "Imesimamishwa kwenye {device}",
    )

    private fun TA(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "இந்த சாதனத்தில் காஸ்டிங் கிடைக்கவில்லை.",
        "plugin.cast-sender.connecting" to "{device} உடன் இணைக்கப்படுகிறது…",
        "plugin.cast-sender.connected" to "{device} க்கு அனுப்பப்படுகிறது",
        "plugin.cast-sender.disconnected" to "{device} இலிருந்து துண்டிக்கப்பட்டது",
        "plugin.cast-sender.error.session-failed" to "காஸ்ட் அமர்வைத் தொடங்க முடியவில்லை.",
        "plugin.cast-sender.error.load-failed" to "காஸ்ட் சாதனம் ஊடகத்தை நிராகரித்தது.",
        "plugin.cast-sender.error.generic" to "ஒரு காஸ்ட் பிழை ஏற்பட்டது.",
        "plugin.cast-sender.action.connect" to "அனுப்பு",
        "plugin.cast-sender.action.disconnect" to "காஸ்ட் செய்வதை நிறுத்து",
        "plugin.cast-sender.state.buffering" to "இடையகப்படுத்துகிறது",
        "plugin.cast-sender.state.playing" to "{device} இல் இயக்கப்படுகிறது",
        "plugin.cast-sender.state.paused" to "{device} இல் இடைநிறுத்தப்பட்டது",
    )

    private fun TE(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ఈ పరికరంలో కాస్టింగ్ అందుబాటులో లేదు.",
        "plugin.cast-sender.connecting" to "{device} కు కనెక్ట్ అవుతోంది…",
        "plugin.cast-sender.connected" to "{device} కు కాస్ట్ చేస్తోంది",
        "plugin.cast-sender.disconnected" to "{device} నుండి డిస్‌కనెక్ట్ చేయబడింది",
        "plugin.cast-sender.error.session-failed" to "క్యాస్ట్ సెషన్‌ను ప్రారంభించలేకపోయాం.",
        "plugin.cast-sender.error.load-failed" to "క్యాస్ట్ పరికరం మీడియాను తిరస్కరించింది.",
        "plugin.cast-sender.error.generic" to "క్యాస్ట్ లోపం సంభవించింది.",
        "plugin.cast-sender.action.connect" to "ప్రసారించు",
        "plugin.cast-sender.action.disconnect" to "క్యాస్ట్ ఆపండి",
        "plugin.cast-sender.state.buffering" to "బఫరింగ్",
        "plugin.cast-sender.state.playing" to "{device}లో ప్లే అవుతోంది",
        "plugin.cast-sender.state.paused" to "{device}లో పాజ్ చేయబడింది",
    )

    private fun TG(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Пахш дар ин дастгоҳ дастрас нест.",
        "plugin.cast-sender.connecting" to "Пайвастшавӣ ба {device}…",
        "plugin.cast-sender.connected" to "Пахш ба {device}",
        "plugin.cast-sender.disconnected" to "Аз {device} ҷудо шуд",
        "plugin.cast-sender.error.session-failed" to "Оғози ҷаласаи интиқол имконнопазир аст.",
        "plugin.cast-sender.error.load-failed" to "Дастгоҳи интиқол медиаро рад кард.",
        "plugin.cast-sender.error.generic" to "Хатои интиқол рух дод.",
        "plugin.cast-sender.action.connect" to "Пахш кардан",
        "plugin.cast-sender.action.disconnect" to "Қатъи интиқол",
        "plugin.cast-sender.state.buffering" to "Буферкунӣ",
        "plugin.cast-sender.state.playing" to "Дар {device} пахш мешавад",
        "plugin.cast-sender.state.paused" to "Дар {device} таваққуф шуд",
    )

    private fun TH(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "ไม่สามารถแคสต์บนอุปกรณ์นี้ได้",
        "plugin.cast-sender.connecting" to "กำลังเชื่อมต่อกับ {device}…",
        "plugin.cast-sender.connected" to "กำลังแคสต์ไปยัง {device}",
        "plugin.cast-sender.disconnected" to "ตัดการเชื่อมต่อจาก {device} แล้ว",
        "plugin.cast-sender.error.session-failed" to "ไม่สามารถเริ่มเซสชันการแคสต์ได้",
        "plugin.cast-sender.error.load-failed" to "อุปกรณ์แคสต์ปฏิเสธสื่อ",
        "plugin.cast-sender.error.generic" to "เกิดข้อผิดพลาดในการแคสต์",
        "plugin.cast-sender.action.connect" to "แคสต์",
        "plugin.cast-sender.action.disconnect" to "หยุดแคสต์",
        "plugin.cast-sender.state.buffering" to "กำลังบัฟเฟอร์",
        "plugin.cast-sender.state.playing" to "กำลังเล่นบน {device}",
        "plugin.cast-sender.state.paused" to "หยุดชั่วคราวบน {device}",
    )

    private fun TL(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Hindi available ang casting sa device na ito.",
        "plugin.cast-sender.connecting" to "Kumokonekta sa {device}…",
        "plugin.cast-sender.connected" to "Kina-cast sa {device}",
        "plugin.cast-sender.disconnected" to "Nadiskonekta mula sa {device}",
        "plugin.cast-sender.error.session-failed" to "Hindi masimulan ang cast session.",
        "plugin.cast-sender.error.load-failed" to "Tinanggihan ng cast device ang media.",
        "plugin.cast-sender.error.generic" to "May naganap na cast error.",
        "plugin.cast-sender.action.connect" to "I-cast",
        "plugin.cast-sender.action.disconnect" to "Itigil ang cast",
        "plugin.cast-sender.state.buffering" to "Nagba-buffer",
        "plugin.cast-sender.state.playing" to "Pinapatugtog sa {device}",
        "plugin.cast-sender.state.paused" to "Naka-pause sa {device}",
    )

    private fun TR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Bu cihazda yayınlama kullanılamıyor.",
        "plugin.cast-sender.connecting" to "{device} cihazına bağlanılıyor…",
        "plugin.cast-sender.connected" to "{device} cihazına yayınlanıyor",
        "plugin.cast-sender.disconnected" to "{device} bağlantısı kesildi",
        "plugin.cast-sender.error.session-failed" to "Yayın oturumu başlatılamadı.",
        "plugin.cast-sender.error.load-failed" to "Yayın cihazı medyayı reddetti.",
        "plugin.cast-sender.error.generic" to "Bir yayın hatası oluştu.",
        "plugin.cast-sender.action.connect" to "Yayınla",
        "plugin.cast-sender.action.disconnect" to "Yayını durdur",
        "plugin.cast-sender.state.buffering" to "Arabelleğe alınıyor",
        "plugin.cast-sender.state.playing" to "{device} cihazında oynatılıyor",
        "plugin.cast-sender.state.paused" to "{device} cihazında duraklatıldı",
    )

    private fun UK(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Трансляція недоступна на цьому пристрої.",
        "plugin.cast-sender.connecting" to "Підключення до {device}…",
        "plugin.cast-sender.connected" to "Трансляція на {device}",
        "plugin.cast-sender.disconnected" to "Від’єднано від {device}",
        "plugin.cast-sender.error.session-failed" to "Не вдалося розпочати сеанс трансляції.",
        "plugin.cast-sender.error.load-failed" to "Пристрій трансляції відхилив медіафайл.",
        "plugin.cast-sender.error.generic" to "Сталася помилка трансляції.",
        "plugin.cast-sender.action.connect" to "Трансляція",
        "plugin.cast-sender.action.disconnect" to "Зупинити трансляцію",
        "plugin.cast-sender.state.buffering" to "Буферизація",
        "plugin.cast-sender.state.playing" to "Відтворюється на {device}",
        "plugin.cast-sender.state.paused" to "Призупинено на {device}",
    )

    private fun UR(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "اس ڈیوائس پر کاسٹنگ دستیاب نہیں ہے۔",
        "plugin.cast-sender.connecting" to "{device} سے منسلک ہو رہا ہے…",
        "plugin.cast-sender.connected" to "{device} پر کاسٹ ہو رہا ہے",
        "plugin.cast-sender.disconnected" to "{device} سے منقطع ہو گیا",
        "plugin.cast-sender.error.session-failed" to "کاسٹ سیشن شروع نہیں کیا جا سکا۔",
        "plugin.cast-sender.error.load-failed" to "کاسٹ ڈیوائس نے میڈیا مسترد کر دیا۔",
        "plugin.cast-sender.error.generic" to "کاسٹ کی خرابی پیش آئی۔",
        "plugin.cast-sender.action.connect" to "نشر کریں",
        "plugin.cast-sender.action.disconnect" to "کاسٹ کرنا بند کریں",
        "plugin.cast-sender.state.buffering" to "بفرنگ",
        "plugin.cast-sender.state.playing" to "{device} پر چل رہا ہے",
        "plugin.cast-sender.state.paused" to "{device} پر روکا گیا",
    )

    private fun UZ(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Bu qurilmada uzatish mavjud emas.",
        "plugin.cast-sender.connecting" to "{device} ga ulanmoqda…",
        "plugin.cast-sender.connected" to "{device} ga uzatilmoqda",
        "plugin.cast-sender.disconnected" to "{device} qurilmasidan uzildi",
        "plugin.cast-sender.error.session-failed" to "Translatsiya seansini boshlab boʻlmadi.",
        "plugin.cast-sender.error.load-failed" to "Translatsiya qurilmasi mediani rad etdi.",
        "plugin.cast-sender.error.generic" to "Translatsiya xatosi yuz berdi.",
        "plugin.cast-sender.action.connect" to "Uzatish",
        "plugin.cast-sender.action.disconnect" to "Translatsiyani toʻxtatish",
        "plugin.cast-sender.state.buffering" to "Buferlash",
        "plugin.cast-sender.state.playing" to "{device} qurilmasida ijro etilmoqda",
        "plugin.cast-sender.state.paused" to "{device} qurilmasida pauza qilindi",
    )

    private fun VI(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Tính năng truyền không khả dụng trên thiết bị này.",
        "plugin.cast-sender.connecting" to "Đang kết nối với {device}…",
        "plugin.cast-sender.connected" to "Đang truyền tới {device}",
        "plugin.cast-sender.disconnected" to "Đã ngắt kết nối khỏi {device}",
        "plugin.cast-sender.error.session-failed" to "Không thể bắt đầu phiên truyền.",
        "plugin.cast-sender.error.load-failed" to "Thiết bị truyền đã từ chối nội dung.",
        "plugin.cast-sender.error.generic" to "Đã xảy ra lỗi truyền.",
        "plugin.cast-sender.action.connect" to "Phát trực tiếp",
        "plugin.cast-sender.action.disconnect" to "Dừng truyền",
        "plugin.cast-sender.state.buffering" to "Đang tải bộ đệm",
        "plugin.cast-sender.state.playing" to "Đang phát trên {device}",
        "plugin.cast-sender.state.paused" to "Đã tạm dừng trên {device}",
    )

    private fun XH(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Ukusasaza akufumaneki kwesi sixhobo.",
        "plugin.cast-sender.connecting" to "Kuqhagamshelwa ku-{device}…",
        "plugin.cast-sender.connected" to "Kusasazwa ku-{device}",
        "plugin.cast-sender.disconnected" to "Inqunyulwe kwi-{device}",
        "plugin.cast-sender.error.session-failed" to "Ayikwazanga ukuqalisa iseshoni yokusasaza.",
        "plugin.cast-sender.error.load-failed" to "Isixhobo sokusasaza siyalile imidiya.",
        "plugin.cast-sender.error.generic" to "Kwenzeke impazamo yokusasaza.",
        "plugin.cast-sender.action.connect" to "Thumela",
        "plugin.cast-sender.action.disconnect" to "Yeka ukusasaza",
        "plugin.cast-sender.state.buffering" to "Iyalayisha",
        "plugin.cast-sender.state.playing" to "Idlala kwi-{device}",
        "plugin.cast-sender.state.paused" to "Inqunyanyisiwe kwi-{device}",
    )

    private fun YO(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Cast kò sí lórí ẹ̀rọ yìí.",
        "plugin.cast-sender.connecting" to "Ń sopọ̀ sí {device}…",
        "plugin.cast-sender.connected" to "Ń ṣe Cast sí {device}",
        "plugin.cast-sender.disconnected" to "Ti ya kúrò lọ́dọ̀ {device}",
        "plugin.cast-sender.error.session-failed" to "Kò lè bẹ̀rẹ̀ ìpàdé ìgbóhùnsáfẹ́fẹ́.",
        "plugin.cast-sender.error.load-failed" to "Ẹ̀rọ ìgbóhùnsáfẹ́fẹ́ kọ media náà.",
        "plugin.cast-sender.error.generic" to "Àṣìṣe ìgbóhùnsáfẹ́fẹ́ kan ṣẹlẹ̀.",
        "plugin.cast-sender.action.connect" to "Tẹ̀léfísọ̀n",
        "plugin.cast-sender.action.disconnect" to "Dúró ìgbóhùnsáfẹ́fẹ́",
        "plugin.cast-sender.state.buffering" to "N ṣe àfipamọ́",
        "plugin.cast-sender.state.playing" to "Ń ṣiṣẹ́ lórí {device}",
        "plugin.cast-sender.state.paused" to "Dúró fún ìgbà díẹ̀ lórí {device}",
    )

    private fun ZH(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "此设备不支持投放。",
        "plugin.cast-sender.connecting" to "正在连接到 {device}…",
        "plugin.cast-sender.connected" to "正在投放到 {device}",
        "plugin.cast-sender.disconnected" to "已断开与 {device} 的连接",
        "plugin.cast-sender.error.session-failed" to "无法启动投放会话。",
        "plugin.cast-sender.error.load-failed" to "投放设备拒绝了该媒体。",
        "plugin.cast-sender.error.generic" to "发生投放错误。",
        "plugin.cast-sender.action.connect" to "投屏",
        "plugin.cast-sender.action.disconnect" to "停止投放",
        "plugin.cast-sender.state.buffering" to "缓冲中",
        "plugin.cast-sender.state.playing" to "正在 {device} 上播放",
        "plugin.cast-sender.state.paused" to "已在 {device} 上暂停",
    )

    private fun ZH_TW(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "此裝置不支援投放。",
        "plugin.cast-sender.connecting" to "正在連線到 {device}…",
        "plugin.cast-sender.connected" to "正在投放到 {device}",
        "plugin.cast-sender.disconnected" to "已中斷與 {device} 的連線",
        "plugin.cast-sender.error.session-failed" to "無法啟動投放工作階段。",
        "plugin.cast-sender.error.load-failed" to "投放裝置拒絕了該媒體。",
        "plugin.cast-sender.error.generic" to "發生投放錯誤。",
        "plugin.cast-sender.action.connect" to "投放",
        "plugin.cast-sender.action.disconnect" to "停止投放",
        "plugin.cast-sender.state.buffering" to "緩衝中",
        "plugin.cast-sender.state.playing" to "正在 {device} 上播放",
        "plugin.cast-sender.state.paused" to "已在 {device} 上暫停",
    )

    private fun ZU(): Map<String, String> = mapOf(
        "plugin.cast-sender.unavailable" to "Ukusakaza akutholakali kule divayisi.",
        "plugin.cast-sender.connecting" to "Kuxhumana ne-{device}…",
        "plugin.cast-sender.connected" to "Kusakazwa ku-{device}",
        "plugin.cast-sender.disconnected" to "Inqamukile ku-{device}",
        "plugin.cast-sender.error.session-failed" to "Ayikwazanga ukuqala iseshini yokusakaza.",
        "plugin.cast-sender.error.load-failed" to "Idivayisi yokusakaza yenqabe imidiya.",
        "plugin.cast-sender.error.generic" to "Kwenzeke iphutha lokusakaza.",
        "plugin.cast-sender.action.connect" to "Thumela",
        "plugin.cast-sender.action.disconnect" to "Misa ukusakaza",
        "plugin.cast-sender.state.buffering" to "Iyalayisha",
        "plugin.cast-sender.state.playing" to "Kudlala ku-{device}",
        "plugin.cast-sender.state.paused" to "Kumiswe okwesikhashana ku-{device}",
    )

    private val LOCALES: Map<String, () -> Map<String, String>> = mapOf(
        "af" to ::AF,
        "ar" to ::AR,
        "bg" to ::BG,
        "bn" to ::BN,
        "ca" to ::CA,
        "cs" to ::CS,
        "cy" to ::CY,
        "da" to ::DA,
        "de" to ::DE,
        "el" to ::EL,
        "en" to ::EN,
        "es" to ::ES,
        "et" to ::ET,
        "eu" to ::EU,
        "fa" to ::FA,
        "fi" to ::FI,
        "fr" to ::FR,
        "ga" to ::GA,
        "gl" to ::GL,
        "gu" to ::GU,
        "he" to ::HE,
        "hi" to ::HI,
        "hr" to ::HR,
        "hu" to ::HU,
        "hy" to ::HY,
        "id" to ::ID,
        "is" to ::IS,
        "it" to ::IT,
        "ja" to ::JA,
        "ka" to ::KA,
        "kk" to ::KK,
        "km" to ::KM,
        "kn" to ::KN,
        "ko" to ::KO,
        "ku" to ::KU,
        "ky" to ::KY,
        "lo" to ::LO,
        "lt" to ::LT,
        "lv" to ::LV,
        "mk" to ::MK,
        "ml" to ::ML,
        "mn" to ::MN,
        "mr" to ::MR,
        "ms" to ::MS,
        "my" to ::MY,
        "nb" to ::NB,
        "ne" to ::NE,
        "nl" to ::NL,
        "nn" to ::NN,
        "no" to ::NO,
        "oc" to ::OC,
        "pa" to ::PA,
        "pl" to ::PL,
        "pt" to ::PT,
        "pt-BR" to ::PT_BR,
        "ro" to ::RO,
        "ru" to ::RU,
        "si" to ::SI,
        "sk" to ::SK,
        "sl" to ::SL,
        "sq" to ::SQ,
        "sr" to ::SR,
        "sv" to ::SV,
        "sw" to ::SW,
        "ta" to ::TA,
        "te" to ::TE,
        "tg" to ::TG,
        "th" to ::TH,
        "tl" to ::TL,
        "tr" to ::TR,
        "uk" to ::UK,
        "ur" to ::UR,
        "uz" to ::UZ,
        "vi" to ::VI,
        "xh" to ::XH,
        "yo" to ::YO,
        "zh" to ::ZH,
        "zh-TW" to ::ZH_TW,
        "zu" to ::ZU,
    )
}
