// -----------------------------------------------------------------------------
//  Copyright (c) NoMercy Entertainment
//
//  Licensed under the Apache License, Version 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------

// Locale tags are the file names, upper-cased, so a reader can find the
// source of any table in one step. Kotlin wants camelCase functions and a
// locale is not a word; renaming them would break that correspondence for
// a convention no human reads here. Lines are long because a translated
// string is as long as it is.
// Repeated literals are the point: many languages share a word, and a
// table that extracted them into constants would stop being readable as
// the source files it mirrors.
@file:Suppress("FunctionNaming", "MaxLineLength", "LargeClass", "StringLiteralDuplication", "LongMethod", "TooManyFunctions")

package tv.nomercy.player.video.input

// The remote handler's strings, in every language it ships.
//
// Generated by scripts/generate-player-translations.py from the same
// tv-key-handler/i18n/*.ts files the browser loads, so a native
// viewer reads the string a web viewer reads rather than a rewording of it.
//
// 79 locales, 9 keys. Generated because hand-maintaining that is how one
// locale silently keeps a string the web changed two releases ago.
//
// Do not edit — regenerate.
public object TvKeyHandlerTranslations {

    // English is the canonical schema on the web: every other file is typed
    // against it, so a key missing anywhere is a compile error there. Here it
    // is the fallback, which is the same guarantee said differently — a
    // locale missing a key reads English rather than reading a key.
    public const val FALLBACK: String = "en"

    // A function per locale, and a map of references rather than of maps.
    //
    // Built the obvious way — one object holding eighty map literals — a
    // table this wide lands in a single static initializer and the JVM
    // refuses the class outright: 'Method too large: <clinit>', because
    // nine thousand entries is past the 64K bytecode limit for one method.
    // The generator emits this shape for every table it writes rather than
    // only the wide ones, so a table that grows does not one day need a
    // different shape than the one its readers were written against.
    //
    // Split like this each locale is its own small method, and the
    // initializer holds eighty references. It also means a player that only
    // ever renders one language only ever builds one map.
    public fun of(locale: String): Map<String, String> =
        (LOCALES[locale] ?: LOCALES[locale.substringBefore('-')] ?: LOCALES.getValue(FALLBACK))()

    // A key with no value in this locale falls back to English rather than
    // rendering the key itself, which is what a viewer sees as
    // 'plugin.tv-key-handler.info.chapter' in the middle of their player.
    public fun get(locale: String, key: String): String =
        of(locale)[key] ?: LOCALES.getValue(FALLBACK)()[key] ?: key

    public val available: Set<String> get() = LOCALES.keys

    private fun AF(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Hoofstuk",
        "plugin.tv-key-handler.info.noTitle" to "Geen titel",
        "plugin.tv-key-handler.info.timeRemaining" to "oorblywend",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Aspekverhouding",
        "plugin.tv-key-handler.bookmark.added" to "Boekmerk bygevoeg",
    )

    private fun AR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "الفصل",
        "plugin.tv-key-handler.info.noTitle" to "بدون عنوان",
        "plugin.tv-key-handler.info.timeRemaining" to "متبقٍ",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "نسبة العرض",
        "plugin.tv-key-handler.bookmark.added" to "تمت إضافة إشارة مرجعية",
    )

    private fun BG(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Глава",
        "plugin.tv-key-handler.info.noTitle" to "Без заглавие",
        "plugin.tv-key-handler.info.timeRemaining" to "оставащо",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Съотношение на страните",
        "plugin.tv-key-handler.bookmark.added" to "Отметката е добавена",
    )

    private fun BN(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "অধ্যায়",
        "plugin.tv-key-handler.info.noTitle" to "কোনো শিরোনাম নেই",
        "plugin.tv-key-handler.info.timeRemaining" to "অবশিষ্ট",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "আকৃতির অনুপাত",
        "plugin.tv-key-handler.bookmark.added" to "বুকমার্ক যোগ করা হয়েছে",
    )

    private fun CA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítol",
        "plugin.tv-key-handler.info.noTitle" to "Sense títol",
        "plugin.tv-key-handler.info.timeRemaining" to "restant",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Relació d\\\\\\\\\\\\\\'aspecte",
        "plugin.tv-key-handler.bookmark.added" to "Marcador afegit",
    )

    private fun CS(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitola",
        "plugin.tv-key-handler.info.noTitle" to "Bez názvu",
        "plugin.tv-key-handler.info.timeRemaining" to "zbývá",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Poměr stran",
        "plugin.tv-key-handler.bookmark.added" to "Záložka přidána",
    )

    private fun CY(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Pennod",
        "plugin.tv-key-handler.info.noTitle" to "Dim teitl",
        "plugin.tv-key-handler.info.timeRemaining" to "ar ôl",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Cymhareb agwedd",
        "plugin.tv-key-handler.bookmark.added" to "Nod tudalen wedi\\'i ychwanegu",
    )

    private fun DA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitel",
        "plugin.tv-key-handler.info.noTitle" to "Ingen titel",
        "plugin.tv-key-handler.info.timeRemaining" to "tilbage",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Billedformat",
        "plugin.tv-key-handler.bookmark.added" to "Bogmærke tilføjet",
    )

    private fun DE(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitel",
        "plugin.tv-key-handler.info.noTitle" to "Kein Titel",
        "plugin.tv-key-handler.info.timeRemaining" to "verbleibend",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Seitenverhältnis",
        "plugin.tv-key-handler.bookmark.added" to "Lesezeichen hinzugefügt",
    )

    private fun EL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Κεφάλαιο",
        "plugin.tv-key-handler.info.noTitle" to "Χωρίς τίτλο",
        "plugin.tv-key-handler.info.timeRemaining" to "απομένουν",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Αναλογία διαστάσεων",
        "plugin.tv-key-handler.bookmark.added" to "Ο σελιδοδείκτης προστέθηκε",
    )

    private fun EN(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Chapter",
        "plugin.tv-key-handler.info.noTitle" to "No title",
        "plugin.tv-key-handler.info.timeRemaining" to "remaining",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Aspect ratio",
        "plugin.tv-key-handler.bookmark.added" to "Bookmark added",
    )

    private fun ES(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítulo",
        "plugin.tv-key-handler.info.noTitle" to "Sin título",
        "plugin.tv-key-handler.info.timeRemaining" to "restante",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Relación de aspecto",
        "plugin.tv-key-handler.bookmark.added" to "Marcador añadido",
    )

    private fun ET(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Peatükk",
        "plugin.tv-key-handler.info.noTitle" to "Pealkiri puudub",
        "plugin.tv-key-handler.info.timeRemaining" to "jäänud",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Kuvasuhe",
        "plugin.tv-key-handler.bookmark.added" to "Järjehoidja lisatud",
    )

    private fun EU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitulua",
        "plugin.tv-key-handler.info.noTitle" to "Titulurik gabe",
        "plugin.tv-key-handler.info.timeRemaining" to "geratzen da",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Aspektu-erlazioa",
        "plugin.tv-key-handler.bookmark.added" to "Laster-marka gehituta",
    )

    private fun FA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "فصل",
        "plugin.tv-key-handler.info.noTitle" to "بدون عنوان",
        "plugin.tv-key-handler.info.timeRemaining" to "باقی‌مانده",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "نسبت تصویر",
        "plugin.tv-key-handler.bookmark.added" to "نشانک افزوده شد",
    )

    private fun FI(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Luku",
        "plugin.tv-key-handler.info.noTitle" to "Ei otsikkoa",
        "plugin.tv-key-handler.info.timeRemaining" to "jäljellä",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Kuvasuhde",
        "plugin.tv-key-handler.bookmark.added" to "Kirjanmerkki lisätty",
    )

    private fun FR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Chapitre",
        "plugin.tv-key-handler.info.noTitle" to "Aucun titre",
        "plugin.tv-key-handler.info.timeRemaining" to "restant",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Rapport d\\\\\\\\\\\\\\'aspect",
        "plugin.tv-key-handler.bookmark.added" to "Signet ajouté",
    )

    private fun GA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Caibidil",
        "plugin.tv-key-handler.info.noTitle" to "Gan teideal",
        "plugin.tv-key-handler.info.timeRemaining" to "fágtha",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Cóimheas gné",
        "plugin.tv-key-handler.bookmark.added" to "Leabharmharc curtha leis",
    )

    private fun GL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítulo",
        "plugin.tv-key-handler.info.noTitle" to "Sen título",
        "plugin.tv-key-handler.info.timeRemaining" to "restante",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Relación de aspecto",
        "plugin.tv-key-handler.bookmark.added" to "Marcador engadido",
    )

    private fun GU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "પ્રકરણ",
        "plugin.tv-key-handler.info.noTitle" to "કોઈ શીર્ષક નથી",
        "plugin.tv-key-handler.info.timeRemaining" to "બાકી",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "આસ્પેક્ટ રેશિયો",
        "plugin.tv-key-handler.bookmark.added" to "બુકમાર્ક ઉમેરાયું",
    )

    private fun HE(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "פרק",
        "plugin.tv-key-handler.info.noTitle" to "ללא כותרת",
        "plugin.tv-key-handler.info.timeRemaining" to "נותרו",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "יחס גובה-רוחב",
        "plugin.tv-key-handler.bookmark.added" to "סימנייה נוספה",
    )

    private fun HI(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "अध्याय",
        "plugin.tv-key-handler.info.noTitle" to "कोई शीर्षक नहीं",
        "plugin.tv-key-handler.info.timeRemaining" to "शेष",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "आस्पेक्ट रेशियो",
        "plugin.tv-key-handler.bookmark.added" to "बुकमार्क जोड़ा गया",
    )

    private fun HR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Poglavlje",
        "plugin.tv-key-handler.info.noTitle" to "Bez naslova",
        "plugin.tv-key-handler.info.timeRemaining" to "preostalo",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Omjer slike",
        "plugin.tv-key-handler.bookmark.added" to "Knjižna oznaka dodana",
    )

    private fun HU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Fejezet",
        "plugin.tv-key-handler.info.noTitle" to "Nincs cím",
        "plugin.tv-key-handler.info.timeRemaining" to "hátralévő",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Képarány",
        "plugin.tv-key-handler.bookmark.added" to "Könyvjelző hozzáadva",
    )

    private fun HY(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Գլուխ",
        "plugin.tv-key-handler.info.noTitle" to "Վերնագիր չկա",
        "plugin.tv-key-handler.info.timeRemaining" to "մնացել է",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Կողմի հարաբերություն",
        "plugin.tv-key-handler.bookmark.added" to "Էջանիշն ավելացվեց",
    )

    private fun ID(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Bab",
        "plugin.tv-key-handler.info.noTitle" to "Tanpa judul",
        "plugin.tv-key-handler.info.timeRemaining" to "tersisa",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Rasio aspek",
        "plugin.tv-key-handler.bookmark.added" to "Markah ditambahkan",
    )

    private fun IS(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kafli",
        "plugin.tv-key-handler.info.noTitle" to "Enginn titill",
        "plugin.tv-key-handler.info.timeRemaining" to "eftir",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Myndhlutfall",
        "plugin.tv-key-handler.bookmark.added" to "Bókamerki bætt við",
    )

    private fun IT(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capitolo",
        "plugin.tv-key-handler.info.noTitle" to "Nessun titolo",
        "plugin.tv-key-handler.info.timeRemaining" to "rimanente",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Rapporto d\\\\\\\\\\\\\\'aspetto",
        "plugin.tv-key-handler.bookmark.added" to "Segnalibro aggiunto",
    )

    private fun JA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "チャプター",
        "plugin.tv-key-handler.info.noTitle" to "タイトルなし",
        "plugin.tv-key-handler.info.timeRemaining" to "残り",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "アスペクト比",
        "plugin.tv-key-handler.bookmark.added" to "ブックマークを追加しました",
    )

    private fun KA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "თავი",
        "plugin.tv-key-handler.info.noTitle" to "სათაური არ არის",
        "plugin.tv-key-handler.info.timeRemaining" to "დარჩა",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "ასპექტის თანაფარდობა",
        "plugin.tv-key-handler.bookmark.added" to "სანიშნე დაემატა",
    )

    private fun KK(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Тарау",
        "plugin.tv-key-handler.info.noTitle" to "Атауы жоқ",
        "plugin.tv-key-handler.info.timeRemaining" to "қалды",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Кадр пропорциясы",
        "plugin.tv-key-handler.bookmark.added" to "Бетбелгі қосылды",
    )

    private fun KM(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "ជំពូក",
        "plugin.tv-key-handler.info.noTitle" to "គ្មានចំណងជើង",
        "plugin.tv-key-handler.info.timeRemaining" to "នៅសល់",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "សមាមាត្រអេក្រង់",
        "plugin.tv-key-handler.bookmark.added" to "បានបន្ថែមចំណាំ",
    )

    private fun KN(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "ಅಧ್ಯಾಯ",
        "plugin.tv-key-handler.info.noTitle" to "ಶೀರ್ಷಿಕೆ ಇಲ್ಲ",
        "plugin.tv-key-handler.info.timeRemaining" to "ಉಳಿದಿದೆ",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "ಆಕಾರ ಅನುಪಾತ",
        "plugin.tv-key-handler.bookmark.added" to "ಬುಕ್‌ಮಾರ್ಕ್ ಸೇರಿಸಲಾಗಿದೆ",
    )

    private fun KO(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "챕터",
        "plugin.tv-key-handler.info.noTitle" to "제목 없음",
        "plugin.tv-key-handler.info.timeRemaining" to "남음",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "화면 비율",
        "plugin.tv-key-handler.bookmark.added" to "북마크 추가됨",
    )

    private fun KU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Beş",
        "plugin.tv-key-handler.info.noTitle" to "Sernav tune",
        "plugin.tv-key-handler.info.timeRemaining" to "mayî",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Rêjeya dîmenê",
        "plugin.tv-key-handler.bookmark.added" to "Şûnpel hat zêdekirin",
    )

    private fun KY(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Бөлүм",
        "plugin.tv-key-handler.info.noTitle" to "Аталышы жок",
        "plugin.tv-key-handler.info.timeRemaining" to "калды",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Кадр катышы",
        "plugin.tv-key-handler.bookmark.added" to "Чөп кат кошулду",
    )

    private fun LO(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "ບົດ",
        "plugin.tv-key-handler.info.noTitle" to "ບໍ່ມີຫົວຂໍ້",
        "plugin.tv-key-handler.info.timeRemaining" to "ຍັງເຫຼືອ",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "ອັດຕາສ່ວນໜ້າຈໍ",
        "plugin.tv-key-handler.bookmark.added" to "ເພີ່ມບຸກມາກແລ້ວ",
    )

    private fun LT(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Skyrius",
        "plugin.tv-key-handler.info.noTitle" to "Nėra pavadinimo",
        "plugin.tv-key-handler.info.timeRemaining" to "liko",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Kraštinių santykis",
        "plugin.tv-key-handler.bookmark.added" to "Žymė pridėta",
    )

    private fun LV(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Nodaļa",
        "plugin.tv-key-handler.info.noTitle" to "Nav nosaukuma",
        "plugin.tv-key-handler.info.timeRemaining" to "atlicis",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Malu attiecība",
        "plugin.tv-key-handler.bookmark.added" to "Grāmatzīme pievienota",
    )

    private fun MK(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Поглавје",
        "plugin.tv-key-handler.info.noTitle" to "Без наслов",
        "plugin.tv-key-handler.info.timeRemaining" to "преостанато",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Сооднос на страни",
        "plugin.tv-key-handler.bookmark.added" to "Обележувачот е додаден",
    )

    private fun ML(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "അധ്യായം",
        "plugin.tv-key-handler.info.noTitle" to "ശീർഷകമില്ല",
        "plugin.tv-key-handler.info.timeRemaining" to "ശേഷിക്കുന്നു",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "ആസ്പെക്ട് റേഷ്യോ",
        "plugin.tv-key-handler.bookmark.added" to "ബുക്ക്മാർക്ക് ചേർത്തു",
    )

    private fun MN(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Бүлэг",
        "plugin.tv-key-handler.info.noTitle" to "Гарчиггүй",
        "plugin.tv-key-handler.info.timeRemaining" to "үлдсэн",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Дэлгэцийн харьцаа",
        "plugin.tv-key-handler.bookmark.added" to "Хавчуурга нэмэгдлээ",
    )

    private fun MR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "प्रकरण",
        "plugin.tv-key-handler.info.noTitle" to "शीर्षक नाही",
        "plugin.tv-key-handler.info.timeRemaining" to "उर्वरित",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "गुणोत्तर",
        "plugin.tv-key-handler.bookmark.added" to "बुकमार्क जोडले",
    )

    private fun MS(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Bab",
        "plugin.tv-key-handler.info.noTitle" to "Tiada tajuk",
        "plugin.tv-key-handler.info.timeRemaining" to "berbaki",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Nisbah aspek",
        "plugin.tv-key-handler.bookmark.added" to "Penanda buku ditambah",
    )

    private fun MY(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "အခန်း",
        "plugin.tv-key-handler.info.noTitle" to "ခေါင်းစဉ်မရှိ",
        "plugin.tv-key-handler.info.timeRemaining" to "ကျန်ရှိ",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "အချိုးအစား",
        "plugin.tv-key-handler.bookmark.added" to "မှတ်သားချက် ထည့်ပြီးပါပြီ",
    )

    private fun NB(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapittel",
        "plugin.tv-key-handler.info.noTitle" to "Ingen tittel",
        "plugin.tv-key-handler.info.timeRemaining" to "gjenstår",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Bildeformat",
        "plugin.tv-key-handler.bookmark.added" to "Bokmerke lagt til",
    )

    private fun NE(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "अध्याय",
        "plugin.tv-key-handler.info.noTitle" to "शीर्षक छैन",
        "plugin.tv-key-handler.info.timeRemaining" to "बाँकी",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "पक्ष अनुपात",
        "plugin.tv-key-handler.bookmark.added" to "बुकमार्क थपियो",
    )

    private fun NL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Hoofdstuk",
        "plugin.tv-key-handler.info.noTitle" to "Geen titel",
        "plugin.tv-key-handler.info.timeRemaining" to "resterend",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Beeldverhouding",
        "plugin.tv-key-handler.bookmark.added" to "Bladwijzer toegevoegd",
    )

    private fun NN(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapittel",
        "plugin.tv-key-handler.info.noTitle" to "Ingen tittel",
        "plugin.tv-key-handler.info.timeRemaining" to "att",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Biletformat",
        "plugin.tv-key-handler.bookmark.added" to "Bokmerke lagt til",
    )

    private fun NO(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapittel",
        "plugin.tv-key-handler.info.noTitle" to "Ingen tittel",
        "plugin.tv-key-handler.info.timeRemaining" to "gjenstår",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Bildeformat",
        "plugin.tv-key-handler.bookmark.added" to "Bokmerke lagt til",
    )

    private fun OC(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítol",
        "plugin.tv-key-handler.info.noTitle" to "Pas cap de títol",
        "plugin.tv-key-handler.info.timeRemaining" to "restant",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Rfo de format",
        "plugin.tv-key-handler.bookmark.added" to "Marcapagina apondut",
    )

    private fun PA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "ਅਧਿਆਇ",
        "plugin.tv-key-handler.info.noTitle" to "ਕੋਈ ਸਿਰਲੇਖ ਨਹੀਂ",
        "plugin.tv-key-handler.info.timeRemaining" to "ਬਾਕੀ",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "ਆਕਾਰ ਅਨੁਪਾਤ",
        "plugin.tv-key-handler.bookmark.added" to "ਬੁੱਕਮਾਰਕ ਸ਼ਾਮਲ ਕੀਤਾ",
    )

    private fun PL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Rozdział",
        "plugin.tv-key-handler.info.noTitle" to "Brak tytułu",
        "plugin.tv-key-handler.info.timeRemaining" to "pozostało",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Proporcje obrazu",
        "plugin.tv-key-handler.bookmark.added" to "Dodano zakładkę",
    )

    private fun PT(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítulo",
        "plugin.tv-key-handler.info.noTitle" to "Sem título",
        "plugin.tv-key-handler.info.timeRemaining" to "restante",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Proporção",
        "plugin.tv-key-handler.bookmark.added" to "Marcador adicionado",
    )

    private fun PT_BR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capítulo",
        "plugin.tv-key-handler.info.noTitle" to "Sem título",
        "plugin.tv-key-handler.info.timeRemaining" to "restante",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Proporção",
        "plugin.tv-key-handler.bookmark.added" to "Marcador adicionado",
    )

    private fun RO(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Capitol",
        "plugin.tv-key-handler.info.noTitle" to "Fără titlu",
        "plugin.tv-key-handler.info.timeRemaining" to "rămas",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Raport de aspect",
        "plugin.tv-key-handler.bookmark.added" to "Marcaj adăugat",
    )

    private fun RU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Глава",
        "plugin.tv-key-handler.info.noTitle" to "Без названия",
        "plugin.tv-key-handler.info.timeRemaining" to "осталось",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Соотношение сторон",
        "plugin.tv-key-handler.bookmark.added" to "Закладка добавлена",
    )

    private fun SI(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "පරිච්ඡේදය",
        "plugin.tv-key-handler.info.noTitle" to "මාතෘකාවක් නැත",
        "plugin.tv-key-handler.info.timeRemaining" to "ඉතිරිව",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "දර්ශන අනුපාතය",
        "plugin.tv-key-handler.bookmark.added" to "පිටුසලකුණ එක් කරන ලදී",
    )

    private fun SK(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitola",
        "plugin.tv-key-handler.info.noTitle" to "Bez názvu",
        "plugin.tv-key-handler.info.timeRemaining" to "zostáva",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Pomer strán",
        "plugin.tv-key-handler.bookmark.added" to "Záložka pridaná",
    )

    private fun SL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Poglavje",
        "plugin.tv-key-handler.info.noTitle" to "Brez naslova",
        "plugin.tv-key-handler.info.timeRemaining" to "preostalo",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Razmerje stranic",
        "plugin.tv-key-handler.bookmark.added" to "Zaznamek dodan",
    )

    private fun SQ(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitulli",
        "plugin.tv-key-handler.info.noTitle" to "Pa titull",
        "plugin.tv-key-handler.info.timeRemaining" to "mbetur",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Raporti i pamjes",
        "plugin.tv-key-handler.bookmark.added" to "Faqerojtësi u shtua",
    )

    private fun SR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Поглавље",
        "plugin.tv-key-handler.info.noTitle" to "Без наслова",
        "plugin.tv-key-handler.info.timeRemaining" to "преостало",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Однос страница",
        "plugin.tv-key-handler.bookmark.added" to "Обележивач је додат",
    )

    private fun SV(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kapitel",
        "plugin.tv-key-handler.info.noTitle" to "Ingen titel",
        "plugin.tv-key-handler.info.timeRemaining" to "kvar",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Bildförhållande",
        "plugin.tv-key-handler.bookmark.added" to "Bokmärke tillagt",
    )

    private fun SW(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Sura",
        "plugin.tv-key-handler.info.noTitle" to "Hakuna kichwa",
        "plugin.tv-key-handler.info.timeRemaining" to "iliyobaki",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Uwiano wa skrini",
        "plugin.tv-key-handler.bookmark.added" to "Alamisho imeongezwa",
    )

    private fun TA(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "அத்தியாயம்",
        "plugin.tv-key-handler.info.noTitle" to "தலைப்பு இல்லை",
        "plugin.tv-key-handler.info.timeRemaining" to "மீதம்",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "விகிதம்",
        "plugin.tv-key-handler.bookmark.added" to "புக்மார்க் சேர்க்கப்பட்டது",
    )

    private fun TE(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "అధ్యాయం",
        "plugin.tv-key-handler.info.noTitle" to "శీర్షిక లేదు",
        "plugin.tv-key-handler.info.timeRemaining" to "మిగిలి ఉంది",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "కొలత నిష్పత్తి",
        "plugin.tv-key-handler.bookmark.added" to "బుక్‌మార్క్ జోడించబడింది",
    )

    private fun TG(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Боб",
        "plugin.tv-key-handler.info.noTitle" to "Бе унвон",
        "plugin.tv-key-handler.info.timeRemaining" to "боқимонда",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Таносуби тасвир",
        "plugin.tv-key-handler.bookmark.added" to "Хатчӯб илова шуд",
    )

    private fun TH(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "บท",
        "plugin.tv-key-handler.info.noTitle" to "ไม่มีชื่อ",
        "plugin.tv-key-handler.info.timeRemaining" to "เหลืออยู่",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "อัตราส่วนภาพ",
        "plugin.tv-key-handler.bookmark.added" to "เพิ่มที่คั่นแล้ว",
    )

    private fun TL(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Kabanata",
        "plugin.tv-key-handler.info.noTitle" to "Walang pamagat",
        "plugin.tv-key-handler.info.timeRemaining" to "natitira",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Aspect ratio",
        "plugin.tv-key-handler.bookmark.added" to "Naidagdag ang bookmark",
    )

    private fun TR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Bölüm",
        "plugin.tv-key-handler.info.noTitle" to "Başlık yok",
        "plugin.tv-key-handler.info.timeRemaining" to "kalan",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "En-boy oranı",
        "plugin.tv-key-handler.bookmark.added" to "Yer işareti eklendi",
    )

    private fun UK(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Розділ",
        "plugin.tv-key-handler.info.noTitle" to "Без назви",
        "plugin.tv-key-handler.info.timeRemaining" to "залишилось",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Співвідношення сторін",
        "plugin.tv-key-handler.bookmark.added" to "Закладку додано",
    )

    private fun UR(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "باب",
        "plugin.tv-key-handler.info.noTitle" to "کوئی عنوان نہیں",
        "plugin.tv-key-handler.info.timeRemaining" to "باقی",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "پہلو تناسب",
        "plugin.tv-key-handler.bookmark.added" to "بک مارک شامل کر دیا گیا",
    )

    private fun UZ(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Bob",
        "plugin.tv-key-handler.info.noTitle" to "Sarlavhasiz",
        "plugin.tv-key-handler.info.timeRemaining" to "qoldi",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Tomonlar nisbati",
        "plugin.tv-key-handler.bookmark.added" to "Xatcho‘p qo‘shildi",
    )

    private fun VI(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Chương",
        "plugin.tv-key-handler.info.noTitle" to "Không có tiêu đề",
        "plugin.tv-key-handler.info.timeRemaining" to "còn lại",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Tỷ lệ khung hình",
        "plugin.tv-key-handler.bookmark.added" to "Đã thêm dấu trang",
    )

    private fun XH(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Isahluko",
        "plugin.tv-key-handler.info.noTitle" to "Akukho sihloko",
        "plugin.tv-key-handler.info.timeRemaining" to "eseleyo",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Umlinganiselo wembonakalo",
        "plugin.tv-key-handler.bookmark.added" to "Uphawu longeziwe",
    )

    private fun YO(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Orí",
        "plugin.tv-key-handler.info.noTitle" to "Kò sí àkòlé",
        "plugin.tv-key-handler.info.timeRemaining" to "tó kù",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Ìwọ̀n ìrísí",
        "plugin.tv-key-handler.bookmark.added" to "Àmì ìwé ti fi kún",
    )

    private fun ZH(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "章节",
        "plugin.tv-key-handler.info.noTitle" to "无标题",
        "plugin.tv-key-handler.info.timeRemaining" to "剩余",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "宽高比",
        "plugin.tv-key-handler.bookmark.added" to "已添加书签",
    )

    private fun ZH_TW(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "章節",
        "plugin.tv-key-handler.info.noTitle" to "無標題",
        "plugin.tv-key-handler.info.timeRemaining" to "剩餘",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "長寬比",
        "plugin.tv-key-handler.bookmark.added" to "已加入書籤",
    )

    private fun ZU(): Map<String, String> = mapOf(
        "plugin.tv-key-handler.info.chapter" to "Isahluko",
        "plugin.tv-key-handler.info.noTitle" to "Asikho isihloko",
        "plugin.tv-key-handler.info.timeRemaining" to "esiseleyo",
        "plugin.tv-key-handler.seek.red" to "+30s",
        "plugin.tv-key-handler.seek.green" to "+60s",
        "plugin.tv-key-handler.seek.yellow" to "+90s",
        "plugin.tv-key-handler.seek.blue" to "+120s",
        "plugin.tv-key-handler.aspectRatio.cycled" to "Isilinganiso sokubukeka",
        "plugin.tv-key-handler.bookmark.added" to "Ibhukimaki lengeziwe",
    )

    private val LOCALES: Map<String, () -> Map<String, String>> = mapOf(
        "af" to ::AF,
        "ar" to ::AR,
        "bg" to ::BG,
        "bn" to ::BN,
        "ca" to ::CA,
        "cs" to ::CS,
        "cy" to ::CY,
        "da" to ::DA,
        "de" to ::DE,
        "el" to ::EL,
        "en" to ::EN,
        "es" to ::ES,
        "et" to ::ET,
        "eu" to ::EU,
        "fa" to ::FA,
        "fi" to ::FI,
        "fr" to ::FR,
        "ga" to ::GA,
        "gl" to ::GL,
        "gu" to ::GU,
        "he" to ::HE,
        "hi" to ::HI,
        "hr" to ::HR,
        "hu" to ::HU,
        "hy" to ::HY,
        "id" to ::ID,
        "is" to ::IS,
        "it" to ::IT,
        "ja" to ::JA,
        "ka" to ::KA,
        "kk" to ::KK,
        "km" to ::KM,
        "kn" to ::KN,
        "ko" to ::KO,
        "ku" to ::KU,
        "ky" to ::KY,
        "lo" to ::LO,
        "lt" to ::LT,
        "lv" to ::LV,
        "mk" to ::MK,
        "ml" to ::ML,
        "mn" to ::MN,
        "mr" to ::MR,
        "ms" to ::MS,
        "my" to ::MY,
        "nb" to ::NB,
        "ne" to ::NE,
        "nl" to ::NL,
        "nn" to ::NN,
        "no" to ::NO,
        "oc" to ::OC,
        "pa" to ::PA,
        "pl" to ::PL,
        "pt" to ::PT,
        "pt-BR" to ::PT_BR,
        "ro" to ::RO,
        "ru" to ::RU,
        "si" to ::SI,
        "sk" to ::SK,
        "sl" to ::SL,
        "sq" to ::SQ,
        "sr" to ::SR,
        "sv" to ::SV,
        "sw" to ::SW,
        "ta" to ::TA,
        "te" to ::TE,
        "tg" to ::TG,
        "th" to ::TH,
        "tl" to ::TL,
        "tr" to ::TR,
        "uk" to ::UK,
        "ur" to ::UR,
        "uz" to ::UZ,
        "vi" to ::VI,
        "xh" to ::XH,
        "yo" to ::YO,
        "zh" to ::ZH,
        "zh-TW" to ::ZH_TW,
        "zu" to ::ZU,
    )
}
